//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonInstallDirectories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonInstallDirectories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools.Resources.CommonInstallDirectories", typeof(CommonInstallDirectories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files/SquareEnix/FINAL FANTASY XIV - A Realm Reborn/game/sqpack/ffxiv.
        /// </summary>
        internal static string ProgramFiles_x64 {
            get {
                return ResourceManager.GetString("ProgramFiles_x64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files (x86)/SquareEnix/FINAL FANTASY XIV - A Realm Reborn/game/sqpack/ffxiv.
        /// </summary>
        internal static string ProgramFiles_x86 {
            get {
                return ResourceManager.GetString("ProgramFiles_x86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files/Steam/SteamApps/common/FINAL FANTASY XIV - A Realm Reborn/game/sqpack/ffxiv.
        /// </summary>
        internal static string Steam_ARR_x64 {
            get {
                return ResourceManager.GetString("Steam_ARR_x64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files (x86)/Steam/SteamApps/common/FINAL FANTASY XIV - A Realm Reborn/game/sqpack/ffxiv.
        /// </summary>
        internal static string Steam_ARR_x86 {
            get {
                return ResourceManager.GetString("Steam_ARR_x86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files/Steam/SteamApps/common/FINAL FANTASY XIV Online/game/sqpack/ffxiv.
        /// </summary>
        internal static string Steam_Online_x64 {
            get {
                return ResourceManager.GetString("Steam_Online_x64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files (x86)/Steam/SteamApps/common/FINAL FANTASY XIV Online/game/sqpack/ffxiv.
        /// </summary>
        internal static string Steam_Online_x86 {
            get {
                return ResourceManager.GetString("Steam_Online_x86", resourceCulture);
            }
        }
    }
}
