//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools.Resources.UIMessages", typeof(UIMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t add more texture part 的本地化字符串。
        /// </summary>
        internal static string AddNewTexturePartErrorMessage {
            get {
                return ResourceManager.GetString("AddNewTexturePartErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently only supports &quot;Gear&quot;, &quot;Character&quot;, please contact esrin if necessary. 的本地化字符串。
        /// </summary>
        internal static string AddNewTexturePartErrorMessageWrongCategoryOfItem {
            get {
                return ResourceManager.GetString("AddNewTexturePartErrorMessageWrongCategoryOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Face Paint&quot;,&quot;Equipment Decals&quot; Unsupported. 的本地化字符串。
        /// </summary>
        internal static string AddNewTexturePartErrorMessageWrongItemCategoryOfItem {
            get {
                return ResourceManager.GetString("AddNewTexturePartErrorMessageWrongItemCategoryOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Add New Texture Part 的本地化字符串。
        /// </summary>
        internal static string AddNewTexturePartErrorTitle {
            get {
                return ResourceManager.GetString("AddNewTexturePartErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to add diffuse mapping?
        ///Selecting Yes will add a diffuse map, and selecting No will add a default map. 的本地化字符串。
        /// </summary>
        internal static string AddNewTexturePartQuestionMessage {
            get {
                return ResourceManager.GetString("AddNewTexturePartQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Diffuse Mapping 的本地化字符串。
        /// </summary>
        internal static string AddNewTexturePartQuestionTitle {
            get {
                return ResourceManager.GetString("AddNewTexturePartQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Import Error 的本地化字符串。
        /// </summary>
        internal static string AdvancedImportErrorTitle {
            get {
                return ResourceManager.GetString("AdvancedImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error building Advanced Import Window.
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string AdvancedImportWindowErrorMessage {
            get {
                return ResourceManager.GetString("AdvancedImportWindowErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The index files have been successfully backed up. 的本地化字符串。
        /// </summary>
        internal static string BackupCompleteMessage {
            get {
                return ResourceManager.GetString("BackupCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Complete 的本地化字符串。
        /// </summary>
        internal static string BackupCompleteTitle {
            get {
                return ResourceManager.GetString("BackupCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create backup files.
        ///
        ///Error Message:
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string BackupFailedErrorMessage {
            get {
                return ResourceManager.GetString("BackupFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Creation Failed 的本地化字符串。
        /// </summary>
        internal static string BackupFailedTitle {
            get {
                return ResourceManager.GetString("BackupFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Files Missing 的本地化字符串。
        /// </summary>
        internal static string BackupFilesMissingTitle {
            get {
                return ResourceManager.GetString("BackupFilesMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Accessing Index Backups Folder
        ///
        ///Please set your Index Backups directory in Options &gt; Customize and try again.
        /// 的本地化字符串。
        /// </summary>
        internal static string BackupFolderAccessErrorMessage {
            get {
                return ResourceManager.GetString("BackupFolderAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find backup directory 的本地化字符串。
        /// </summary>
        internal static string BackupsDirectoryErrorMessage {
            get {
                return ResourceManager.GetString("BackupsDirectoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColorSet BMP import is not supported. 的本地化字符串。
        /// </summary>
        internal static string ColorSetBMPNotSupportedMessage {
            get {
                return ResourceManager.GetString("ColorSetBMPNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will create a backup of the commonly modified index files (0a, 01, 04, 06)
        ///
        ///
        ///Do you want to Backup Now?
        ///
        ///
        ///Warning:
        ///In order to create a clean backup, all active modifications will be set to disabled, they will have to be re-enabled manually. 的本地化字符串。
        /// </summary>
        internal static string CreateBackupsMessage {
            get {
                return ResourceManager.GetString("CreateBackupsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Index Files 的本地化字符串。
        /// </summary>
        internal static string CreateBackupsTitle {
            get {
                return ResourceManager.GetString("CreateBackupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Backup? 的本地化字符串。
        /// </summary>
        internal static string CreateBackupTitle {
            get {
                return ResourceManager.GetString("CreateBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error attempting to export the model as a dae.
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string DAEExportErrorMessage {
            get {
                return ResourceManager.GetString("DAEExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error exporting DAE 的本地化字符串。
        /// </summary>
        internal static string DAEExportErrorTitle {
            get {
                return ResourceManager.GetString("DAEExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error attempting to import the model.
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string DAEImportErrorMessage {
            get {
                return ResourceManager.GetString("DAEImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Importing DAE 的本地化字符串。
        /// </summary>
        internal static string DAEImportErrorTitle {
            get {
                return ResourceManager.GetString("DAEImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error attempting to read the DAE file.
        ///
        ///Error: {0} 的本地化字符串。
        /// </summary>
        internal static string DAEReadErrorMessage {
            get {
                return ResourceManager.GetString("DAEReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Reading DAE 的本地化字符串。
        /// </summary>
        internal static string DAEReadErrorTitle {
            get {
                return ResourceManager.GetString("DAEReadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing was entered for ModPack Description
        ///
        ///Description will be left empty. 的本地化字符串。
        /// </summary>
        internal static string DefaultDescriptionMessage {
            get {
                return ResourceManager.GetString("DefaultDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing was entered for ModPack Author
        ///
        ///Author will default to &quot;TexTools User&quot; 的本地化字符串。
        /// </summary>
        internal static string DefaultModPackAuthorMessage {
            get {
                return ResourceManager.GetString("DefaultModPackAuthorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing was entered for ModPack Name
        ///
        ///ModPack Name will default to &quot;ModPack&quot; 的本地化字符串。
        /// </summary>
        internal static string DefaultModPackNameMessage {
            get {
                return ResourceManager.GetString("DefaultModPackNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing was entered for ModPack Version
        ///
        ///Version will default to &quot;1.0.0&quot; 的本地化字符串。
        /// </summary>
        internal static string DefaultModPackVersionMessage {
            get {
                return ResourceManager.GetString("DefaultModPackVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will delete the entire group, and all the options in it. 的本地化字符串。
        /// </summary>
        internal static string DeleteGroupMessage {
            get {
                return ResourceManager.GetString("DeleteGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Deletion Warning 的本地化字符串。
        /// </summary>
        internal static string DeleteGroupTitle {
            get {
                return ResourceManager.GetString("DeleteGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caution: This will delete all the mods for the currently selected Mod Pack.
        ///
        ///This process is not reversible, do you want to continue? 的本地化字符串。
        /// </summary>
        internal static string DeleteModPackMessage {
            get {
                return ResourceManager.GetString("DeleteModPackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Pack Deletion Warning. 的本地化字符串。
        /// </summary>
        internal static string DeleteModPackTitle {
            get {
                return ResourceManager.GetString("DeleteModPackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TexTools was unable to locate dependency files.
        ///Please make sure you are running TexTools in the folder it came in.
        ///
        ///If you continue to receive this error,
        ///Please make sure your Anti-Virus is not blocking TexTools.
        ///
        ///Error: {0}
        ///
        ///Exception:{1} 的本地化字符串。
        /// </summary>
        internal static string DependencyErrorMessage {
            get {
                return ResourceManager.GetString("DependencyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependencies Error v{0} 的本地化字符串。
        /// </summary>
        internal static string DependencyErrorTitle {
            get {
                return ResourceManager.GetString("DependencyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will Disable all mods located in the modlist.
        ///
        ///Are you sure you want to proceed? 的本地化字符串。
        /// </summary>
        internal static string DisableAllModsMessage {
            get {
                return ResourceManager.GetString("DisableAllModsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable All Mods 的本地化字符串。
        /// </summary>
        internal static string DisableAllModsTitle {
            get {
                return ResourceManager.GetString("DisableAllModsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabling Mods 的本地化字符串。
        /// </summary>
        internal static string DisablingModsTitle {
            get {
                return ResourceManager.GetString("DisablingModsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TTMP file [ {0} ] is empty.
        ///
        ///Importing Canceled. 的本地化字符串。
        /// </summary>
        internal static string EmptyTTMPFileErrorMessage {
            get {
                return ResourceManager.GetString("EmptyTTMPFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will Enable all mods located in the modlist.
        ///
        ///Are you sure you want to proceed? 的本地化字符串。
        /// </summary>
        internal static string EnableAllModsMessage {
            get {
                return ResourceManager.GetString("EnableAllModsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable All Mods 的本地化字符串。
        /// </summary>
        internal static string EnableAllModsTitle {
            get {
                return ResourceManager.GetString("EnableAllModsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabling Mods 的本地化字符串。
        /// </summary>
        internal static string EnablingModsTitle {
            get {
                return ResourceManager.GetString("EnablingModsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There were errors importing some mods. 的本地化字符串。
        /// </summary>
        internal static string ErrorImportingModsMessage {
            get {
                return ResourceManager.GetString("ErrorImportingModsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Importing Mods 的本地化字符串。
        /// </summary>
        internal static string ErrorImportingModsTitle {
            get {
                return ResourceManager.GetString("ErrorImportingModsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 group already exists, please rename the group.
        ///
        ///If you would like to add to that group instead, go back and click the edit button. 的本地化字符串。
        /// </summary>
        internal static string ExistingGroupMessage {
            get {
                return ResourceManager.GetString("ExistingGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Name already exists. 的本地化字符串。
        /// </summary>
        internal static string ExistingGroupTitle {
            get {
                return ResourceManager.GetString("ExistingGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Option already includes {0}
        ///
        ///Would you like to overwrite the existing mod for this option? 的本地化字符串。
        /// </summary>
        internal static string ExistingOption {
            get {
                return ResourceManager.GetString("ExistingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TexTools was unable to determine the game version. 的本地化字符串。
        /// </summary>
        internal static string GameVersionErrorMessage {
            get {
                return ResourceManager.GetString("GameVersionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version Check Error {0} 的本地化字符串。
        /// </summary>
        internal static string GameVersionErrorTitle {
            get {
                return ResourceManager.GetString("GameVersionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Complete 的本地化字符串。
        /// </summary>
        internal static string ImportCompleteTitle {
            get {
                return ResourceManager.GetString("ImportCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Error 的本地化字符串。
        /// </summary>
        internal static string ImportErrorTitle {
            get {
                return ResourceManager.GetString("ImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location of Index Backup folder changed.
        ///
        ///New Location: {0} 的本地化字符串。
        /// </summary>
        internal static string IndexBackupLocationChangedMessage {
            get {
                return ResourceManager.GetString("IndexBackupLocationChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index Backups Error 的本地化字符串。
        /// </summary>
        internal static string IndexBackupsErrorTitle {
            get {
                return ResourceManager.GetString("IndexBackupsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create backup while game is running. 的本地化字符串。
        /// </summary>
        internal static string IndexLockedBackupFailedMessage {
            get {
                return ResourceManager.GetString("IndexLockedBackupFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Accessing Index File
        ///
        ///
        ///Please exit the game before proceeding.
        ///----------------------------------------------------- 的本地化字符串。
        /// </summary>
        internal static string IndexLockedErrorMessage {
            get {
                return ResourceManager.GetString("IndexLockedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index Access Error 的本地化字符串。
        /// </summary>
        internal static string IndexLockedErrorTitle {
            get {
                return ResourceManager.GetString("IndexLockedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFXIV install directory found at
        ///
        ///{0}
        ///
        ///Use this directory? 的本地化字符串。
        /// </summary>
        internal static string InstallDirectoryFoundMessage {
            get {
                return ResourceManager.GetString("InstallDirectoryFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Directory Found 的本地化字符串。
        /// </summary>
        internal static string InstallDirectoryFoundTitle {
            get {
                return ResourceManager.GetString("InstallDirectoryFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please locate the following directory.
        ///
        ///.../FINAL FANTASY XIV - A Realm Reborn/game/sqpack/ffxiv 的本地化字符串。
        /// </summary>
        internal static string InstallDirectoryNotFoundMessage {
            get {
                return ResourceManager.GetString("InstallDirectoryNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Directory Not Found 的本地化字符串。
        /// </summary>
        internal static string InstallDirectoryNotFoundTitle {
            get {
                return ResourceManager.GetString("InstallDirectoryNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error getting the Items List
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ItemsListErrorMessage {
            get {
                return ResourceManager.GetString("ItemsListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items List Error 的本地化字符串。
        /// </summary>
        internal static string ItemsListErrorTitle {
            get {
                return ResourceManager.GetString("ItemsListErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error reading data for the selected language, would you like to revert to English? 
        ///
        ///Language may be changed again later from the Language menu. 的本地化字符串。
        /// </summary>
        internal static string LanguageError {
            get {
                return ResourceManager.GetString("LanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language Data Error 的本地化字符串。
        /// </summary>
        internal static string LanguageErrorTitle {
            get {
                return ResourceManager.GetString("LanguageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Reading Material Data 的本地化字符串。
        /// </summary>
        internal static string MaterialDataReadErrorTitle {
            get {
                return ResourceManager.GetString("MaterialDataReadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error reading the material file {0}
        ///
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string MaterialFileReadErrorMessage {
            get {
                return ResourceManager.GetString("MaterialFileReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error reading the MDL file.
        ///
        ///{0}
        ///
        ///If this error appeared after importing, please submit a bug report with the DAE file attached. 的本地化字符串。
        /// </summary>
        internal static string MDLReadErrorMessage {
            get {
                return ResourceManager.GetString("MDLReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Reading Model Data 的本地化字符串。
        /// </summary>
        internal static string MDLReadErrorTitle {
            get {
                return ResourceManager.GetString("MDLReadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Reading Mod Data 的本地化字符串。
        /// </summary>
        internal static string ModDataReadErrorTitle {
            get {
                return ResourceManager.GetString("ModDataReadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error getting the model data for {0} | {1} 的本地化字符串。
        /// </summary>
        internal static string ModelDataErrorMessage {
            get {
                return ResourceManager.GetString("ModelDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error attempting to import the model.
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ModelImportErrorMessage {
            get {
                return ResourceManager.GetString("ModelImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Importing DAE 的本地化字符串。
        /// </summary>
        internal static string ModelImportErrorTitle {
            get {
                return ResourceManager.GetString("ModelImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModList Disable Failed 的本地化字符串。
        /// </summary>
        internal static string ModListDisableFailedTitle {
            get {
                return ResourceManager.GetString("ModListDisableFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to continue while game is running.
        ///
        ///Please exit the game and try again. 的本地化字符串。
        /// </summary>
        internal static string ModListIndexLockedErrorMessage {
            get {
                return ResourceManager.GetString("ModListIndexLockedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ModPack ({0}.ttmp2) has been successfully Created. 的本地化字符串。
        /// </summary>
        internal static string ModPackCreationCompleteMessage {
            get {
                return ResourceManager.GetString("ModPackCreationCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Pack Creation Complete 的本地化字符串。
        /// </summary>
        internal static string ModPackCreationCompleteTitle {
            get {
                return ResourceManager.GetString("ModPackCreationCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: Mod Pack Creation Failed 的本地化字符串。
        /// </summary>
        internal static string ModPackCreationFailedErrorTitle {
            get {
                return ResourceManager.GetString("ModPackCreationFailedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating ModPack 的本地化字符串。
        /// </summary>
        internal static string ModPackCreationMessage {
            get {
                return ResourceManager.GetString("ModPackCreationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error importing the mod pack at {0}
        ///
        ///Message: {1} 的本地化字符串。
        /// </summary>
        internal static string ModPackImportErrorMessage {
            get {
                return ResourceManager.GetString("ModPackImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModPack Import Error 的本地化字符串。
        /// </summary>
        internal static string ModPackImportErrorTitle {
            get {
                return ResourceManager.GetString("ModPackImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Importing ModPack 的本地化字符串。
        /// </summary>
        internal static string ModPackImportTitle {
            get {
                return ResourceManager.GetString("ModPackImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading ModPack 的本地化字符串。
        /// </summary>
        internal static string ModPackLoadingTitle {
            get {
                return ResourceManager.GetString("ModPackLoadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location of ModPacks folder changed.
        ///
        ///
        ///New Location: {0} 的本地化字符串。
        /// </summary>
        internal static string ModPacksLocationChangedMessage {
            get {
                return ResourceManager.GetString("ModPacksLocationChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Mods were Disabled Successfully 的本地化字符串。
        /// </summary>
        internal static string ModsDisabledSuccessMessage {
            get {
                return ResourceManager.GetString("ModsDisabledSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Mods were Enabled Successfully 的本地化字符串。
        /// </summary>
        internal static string ModsEnabledSuccessMessage {
            get {
                return ResourceManager.GetString("ModsEnabledSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error attempting to toggle mod status. 的本地化字符串。
        /// </summary>
        internal static string ModToggleErrorMessage {
            get {
                return ResourceManager.GetString("ModToggleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Toggling Mod 的本地化字符串。
        /// </summary>
        internal static string ModToggleErrorTitle {
            get {
                return ResourceManager.GetString("ModToggleErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to move the existing data to the new location? 的本地化字符串。
        /// </summary>
        internal static string MoveDataMessage {
            get {
                return ResourceManager.GetString("MoveDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Data? 的本地化字符串。
        /// </summary>
        internal static string MoveDataTitle {
            get {
                return ResourceManager.GetString("MoveDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select new location of Index_Backups folder 的本地化字符串。
        /// </summary>
        internal static string NewBackupLocationTitle {
            get {
                return ResourceManager.GetString("NewBackupLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Directory 的本地化字符串。
        /// </summary>
        internal static string NewDirectoryTitle {
            get {
                return ResourceManager.GetString("NewDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A newer version of FFXIV was detected.
        ///Would you like to create a new backup of your index files now? (Recommended)
        ///
        ///Warning:
        ///In order to create a clean backup, all active modifications will be set to disabled, they will have to be re-enabled manually. 的本地化字符串。
        /// </summary>
        internal static string NewerVersionDetectedBackupMessage {
            get {
                return ResourceManager.GetString("NewerVersionDetectedBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New TexTools Install Detected.
        ///
        ///Would you like to create a new backup of your index files now? (Recommended) 的本地化字符串。
        /// </summary>
        internal static string NewInstallDetectedBackupMessage {
            get {
                return ResourceManager.GetString("NewInstallDetectedBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select new location of ModPacks folder 的本地化字符串。
        /// </summary>
        internal static string newModpacksLocationTitle {
            get {
                return ResourceManager.GetString("newModpacksLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select new location for Saved folder 的本地化字符串。
        /// </summary>
        internal static string NewSaveLocationTitle {
            get {
                return ResourceManager.GetString("NewSaveLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Author Found 的本地化字符串。
        /// </summary>
        internal static string NoAuthorFoundTitle {
            get {
                return ResourceManager.GetString("NoAuthorFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No backup files found in the following directory:
        ///{0}
        ///
        ///
        ///Index entries will be put back to original offsets instead
        ///----------------------------------------------------- 的本地化字符串。
        /// </summary>
        internal static string NoBackupsFoundErrorMessage {
            get {
                return ResourceManager.GetString("NoBackupsFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Index Backups were found. 
        ///Would you like to create a new backup of your index files now? (Recommended) 
        ///
        ///Warning:
        ///In order to create a clean backup, all active modifications will be set to disabled, they will have to be re-enabled manually. 的本地化字符串。
        /// </summary>
        internal static string NoBackupsFoundMessage {
            get {
                return ResourceManager.GetString("NoBackupsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Description Found 的本地化字符串。
        /// </summary>
        internal static string NoDescriptionFoundTitle {
            get {
                return ResourceManager.GetString("NoDescriptionFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No mods were detected in the options list. 的本地化字符串。
        /// </summary>
        internal static string NoModsDetectedErrorMessage {
            get {
                return ResourceManager.GetString("NoModsDetectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Name Found 的本地化字符串。
        /// </summary>
        internal static string NoNameFoundTitle {
            get {
                return ResourceManager.GetString("NoNameFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is not a wizard modPack 的本地化字符串。
        /// </summary>
        internal static string NotWizardModPack {
            get {
                return ResourceManager.GetString("NotWizardModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Version Found 的本地化字符串。
        /// </summary>
        internal static string NoVersionFoundTitle {
            get {
                return ResourceManager.GetString("NoVersionFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error attempting to disable a mod from previous version.
        ///
        ///Error Message:
        ///{0}
        ///
        ///It is recommended to do a Start Over from the previous version first. 的本地化字符串。
        /// </summary>
        internal static string OldModListDisableFailedMessage {
            get {
                return ResourceManager.GetString("OldModListDisableFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Older ModList Found 的本地化字符串。
        /// </summary>
        internal static string OldModListFoundTitle {
            get {
                return ResourceManager.GetString("OldModListFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Older TexTools ModList Found.
        ///
        ///The Older ModList is incompatible with this version.
        ///
        ///In order to use this version, all previous mods will be disabled, and the previous ModList erased.
        ///
        ///
        ///If you would like to retain your mods, it is recommended that you create a backup ModPack in the older TexTools Version, then import it into this one.
        ///
        ///Would you like to continue? 的本地化字符串。
        /// </summary>
        internal static string OldTexToolsFoundMessage {
            get {
                return ResourceManager.GetString("OldTexToolsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index Backups are outdated.
        ///
        ///
        ///Please create a new backup from Help &gt; Backup Index Files
        ///
        ///
        ///TexTools will attempt to start over without using backups. 的本地化字符串。
        /// </summary>
        internal static string OutdatedBackupsErrorMessage {
            get {
                return ResourceManager.GetString("OutdatedBackupsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The install location chosen is out of date
        ///
        ///Please locate the following directory.
        ///
        ///.../FINAL FANTASY XIV - A Realm Reborn/game/sqpack/ffxiv 的本地化字符串。
        /// </summary>
        internal static string OutOfDateInstallMessage {
            get {
                return ResourceManager.GetString("OutOfDateInstallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Directory Out Of Date 的本地化字符串。
        /// </summary>
        internal static string OutOfDateInstallTitle {
            get {
                return ResourceManager.GetString("OutOfDateInstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwrite? 的本地化字符串。
        /// </summary>
        internal static string OverwriteTitle {
            get {
                return ResourceManager.GetString("OverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Stand By... 的本地化字符串。
        /// </summary>
        internal static string PleaseStandByMessage {
            get {
                return ResourceManager.GetString("PleaseStandByMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Wait... 的本地化字符串。
        /// </summary>
        internal static string PleaseWaitMessage {
            get {
                return ResourceManager.GetString("PleaseWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Version Error 的本地化字符串。
        /// </summary>
        internal static string PreviousVersionErrorTitle {
            get {
                return ResourceManager.GetString("PreviousVersionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an issue checking Index Dat Counts 的本地化字符串。
        /// </summary>
        internal static string ProblemCheckDatIssueMessage {
            get {
                return ResourceManager.GetString("ProblemCheckDatIssueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Problem Check Error 的本地化字符串。
        /// </summary>
        internal static string ProblemCheckErrorTitle {
            get {
                return ResourceManager.GetString("ProblemCheckErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an issue obtaining the Raw Data for the mod.
        ///
        ///Offset: {0}
        ///Data File: {1} 的本地化字符串。
        /// </summary>
        internal static string RawDataErrorMessage {
            get {
                return ResourceManager.GetString("RawDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location of Saved folder changed.
        ///
        ///
        ///New Location: {0} 的本地化字符串。
        /// </summary>
        internal static string SavedLocationChangedMessage {
            get {
                return ResourceManager.GetString("SavedLocationChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select sqpack/ffxiv Folder 的本地化字符串。
        /// </summary>
        internal static string SelectffxivFolderTitle {
            get {
                return ResourceManager.GetString("SelectffxivFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The start over process has been completed. 的本地化字符串。
        /// </summary>
        internal static string StartOverCompleteMessage {
            get {
                return ResourceManager.GetString("StartOverCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Over Complete 的本地化字符串。
        /// </summary>
        internal static string StartOverCompleteTitle {
            get {
                return ResourceManager.GetString("StartOverCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting over will:
        ///
        ///Restore index files to their original state.
        ///Delete all mod dat files from game folder.
        ///Delete all mod list file entries.
        ///
        ///Do you want to start over? 的本地化字符串。
        /// </summary>
        internal static string StartOverMessage {
            get {
                return ResourceManager.GetString("StartOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Over 的本地化字符串。
        /// </summary>
        internal static string StartOverTitle {
            get {
                return ResourceManager.GetString("StartOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} mod(s) successfully imported. 的本地化字符串。
        /// </summary>
        internal static string SuccessfulImportCountMessage {
            get {
                return ResourceManager.GetString("SuccessfulImportCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Reading Texture Data 的本地化字符串。
        /// </summary>
        internal static string TextureDataReadErrorTitle {
            get {
                return ResourceManager.GetString("TextureDataReadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error reading the texture file {0}.
        ///
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string TextureFileReadErrorMessage {
            get {
                return ResourceManager.GetString("TextureFileReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error Importing the Texture.
        ///
        ///Error Message:
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string TextureImportErrorMessage {
            get {
                return ResourceManager.GetString("TextureImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Importing Texture 的本地化字符串。
        /// </summary>
        internal static string TextureImportErrorTitle {
            get {
                return ResourceManager.GetString("TextureImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error attempting to toggle translucency
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string TranslucencyToggleErrorMessage {
            get {
                return ResourceManager.GetString("TranslucencyToggleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Toggling Translucency 的本地化字符串。
        /// </summary>
        internal static string TranslucencyToggleErrorTitle {
            get {
                return ResourceManager.GetString("TranslucencyToggleErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Data... 的本地化字符串。
        /// </summary>
        internal static string TTMPGettingData {
            get {
                return ResourceManager.GetString("TTMPGettingData", resourceCulture);
            }
        }
    }
}
