//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About TexTools.
        /// </summary>
        public static string About_TexTools {
            get {
                return ResourceManager.GetString("About_TexTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Model using advanced options.
        /// </summary>
        public static string Add_a_Model_using_advanced_options {
            get {
                return ResourceManager.GetString("Add_a_Model_using_advanced_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        public static string Add_Group {
            get {
                return ResourceManager.GetString("Add_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Texture Part.
        /// </summary>
        public static string Add_NewTexturePart {
            get {
                return ResourceManager.GetString("Add_NewTexturePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove.
        /// </summary>
        public static string Add_Remove {
            get {
                return ResourceManager.GetString("Add_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Part Attribute.
        /// </summary>
        public static string Add_To_Part_Attribute {
            get {
                return ResourceManager.GetString("Add_To_Part_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add w/ Adv. Options.
        /// </summary>
        public static string Add_w_Adv_Options {
            get {
                return ResourceManager.GetString("Add_w_Adv_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added mesh(es)
        ///Change material for new mesh(es) if necessary..
        /// </summary>
        public static string Added_Mesh {
            get {
                return ResourceManager.GetString("Added_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added mesh part(s) for this mesh
        ///Change attributes for new part(s) below if necessary.
        /// </summary>
        public static string Added_MeshParts {
            get {
                return ResourceManager.GetString("Added_MeshParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Import.
        /// </summary>
        public static string Advanced_Import {
            get {
                return ResourceManager.GetString("Advanced_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Model Import.
        /// </summary>
        public static string Advanced_Model_Import {
            get {
                return ResourceManager.GetString("Advanced_Model_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Model Options.
        /// </summary>
        public static string Advanced_Model_Options {
            get {
                return ResourceManager.GetString("Advanced_Model_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string Author_colon {
            get {
                return ResourceManager.GetString("Author_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Attributes.
        /// </summary>
        public static string Available_Attributes {
            get {
                return ResourceManager.GetString("Available_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Index Files.
        /// </summary>
        public static string Backup_Index_Files {
            get {
                return ResourceManager.GetString("Backup_Index_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups Directory.
        /// </summary>
        public static string Backups_Directory {
            get {
                return ResourceManager.GetString("Backups_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG Color.
        /// </summary>
        public static string BG_Color {
            get {
                return ResourceManager.GetString("BG_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bone addition is automatic.
        /// </summary>
        public static string Bone_addition_is_automatic {
            get {
                return ResourceManager.GetString("Bone_addition_is_automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bones.
        /// </summary>
        public static string Bones {
            get {
                return ResourceManager.GetString("Bones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Problems.
        /// </summary>
        public static string Check_For_Problems {
            get {
                return ResourceManager.GetString("Check_For_Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Discord.
        /// </summary>
        public static string ChinaDiscord {
            get {
                return ResourceManager.GetString("ChinaDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected.
        /// </summary>
        public static string Clear_Selected {
            get {
                return ResourceManager.GetString("Clear_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add a preview image.
        /// </summary>
        public static string Clic_here_to_add_a_preview_image {
            get {
                return ResourceManager.GetString("Clic_here_to_add_a_preview_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone UV1 to UV2.
        /// </summary>
        public static string Clone_UV1_to_UV2 {
            get {
                return ResourceManager.GetString("Clone_UV1_to_UV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors &amp;amp; Skins.
        /// </summary>
        public static string Colors_Skins {
            get {
                return ResourceManager.GetString("Colors_Skins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert To.
        /// </summary>
        public static string Convert_To {
            get {
                return ResourceManager.GetString("Convert_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:.
        /// </summary>
        public static string Count_colon {
            get {
                return ResourceManager.GetString("Count_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Modpack.
        /// </summary>
        public static string Create_Modpack {
            get {
                return ResourceManager.GetString("Create_Modpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ModPack Wizard.
        /// </summary>
        public static string Create_ModPack_Wizard {
            get {
                return ResourceManager.GetString("Create_ModPack_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cull Mode.
        /// </summary>
        public static string Cull_Mode {
            get {
                return ResourceManager.GetString("Cull_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Language:.
        /// </summary>
        public static string Current_Language_colon {
            get {
                return ResourceManager.GetString("Current_Language_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TexTools will choose the selected race by default if available when viewing Textures and Models..
        /// </summary>
        public static string Customize_DefaultRace {
            get {
                return ResourceManager.GetString("Customize_DefaultRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAE file to import.
        /// </summary>
        public static string DAE_file_to_import {
            get {
                return ResourceManager.GetString("DAE_file_to_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAE Info.
        /// </summary>
        public static string DAE_Info {
            get {
                return ResourceManager.GetString("DAE_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Skin.
        /// </summary>
        public static string Default_Skin {
            get {
                return ResourceManager.GetString("Default_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All Mods.
        /// </summary>
        public static string Disable_All_Mods {
            get {
                return ResourceManager.GetString("Disable_All_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Shape Data.
        /// </summary>
        public static string Disable_Shape_Data {
            get {
                return ResourceManager.GetString("Disable_Shape_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        public static string Edit_Group {
            get {
                return ResourceManager.GetString("Edit_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable All Mods.
        /// </summary>
        public static string Enable_All_Mods {
            get {
                return ResourceManager.GetString("Enable_All_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable.
        /// </summary>
        public static string Enable_Disable {
            get {
                return ResourceManager.GetString("Enable_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a brief description of your Mod Pack..
        /// </summary>
        public static string Enter_a_brief_description_of_your_Mod_Pack {
            get {
                return ResourceManager.GetString("Enter_a_brief_description_of_your_Mod_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description for the selected option here....
        /// </summary>
        public static string Enter_a_description_for_the_selected_option_here_dot {
            get {
                return ResourceManager.GetString("Enter_a_description_for_the_selected_option_here_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Model ID....
        /// </summary>
        public static string Enter_a_Model_ID_dot {
            get {
                return ResourceManager.GetString("Enter_a_Model_ID_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Name for the Group here.
        /// </summary>
        public static string Enter_a_Name_for_the_Group_here {
            get {
                return ResourceManager.GetString("Enter_a_Name_for_the_Group_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etc Color.
        /// </summary>
        public static string Etc_Color {
            get {
                return ResourceManager.GetString("Etc_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export BMP.
        /// </summary>
        public static string Export_BMP {
            get {
                return ResourceManager.GetString("Export_BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Both.
        /// </summary>
        public static string Export_Both {
            get {
                return ResourceManager.GetString("Export_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export DAE file.
        /// </summary>
        public static string Export_DAE_file {
            get {
                return ResourceManager.GetString("Export_DAE_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export DAE + Materials.
        /// </summary>
        public static string Export_DAE_Materials {
            get {
                return ResourceManager.GetString("Export_DAE_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export DDS.
        /// </summary>
        public static string Export_DDS {
            get {
                return ResourceManager.GetString("Export_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export OBJ files.
        /// </summary>
        public static string Export_OBJ_files {
            get {
                return ResourceManager.GetString("Export_OBJ_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        public static string Export_Settings {
            get {
                return ResourceManager.GetString("Export_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Import Settings.
        /// </summary>
        public static string Extra_Import_Settings {
            get {
                return ResourceManager.GetString("Extra_Import_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFXIV Directory.
        /// </summary>
        public static string FFXIV_Directory {
            get {
                return ResourceManager.GetString("FFXIV_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By:.
        /// </summary>
        public static string Filter_By_colon {
            get {
                return ResourceManager.GetString("Filter_By_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing....
        /// </summary>
        public static string Finalizing {
            get {
                return ResourceManager.GetString("Finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Vertex Alpha.
        /// </summary>
        public static string Flip_Alpha {
            get {
                return ResourceManager.GetString("Flip_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For Translucency or ColorSet).
        /// </summary>
        public static string For_Translucency_or_ColorSet {
            get {
                return ResourceManager.GetString("For_Translucency_or_ColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force UV1 to U1V-1.
        /// </summary>
        public static string Force_UV_Quadrant {
            get {
                return ResourceManager.GetString("Force_UV_Quadrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go through the wizard and select relevant options to import mod pack.
        /// </summary>
        public static string Go_through_the_wizard_and_select_relevant_options_to_import_mod_pack {
            get {
                return ResourceManager.GetString("Go_through_the_wizard_and_select_relevant_options_to_import_mod_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Options.
        /// </summary>
        public static string Group_Options {
            get {
                return ResourceManager.GetString("Group_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Settings.
        /// </summary>
        public static string Group_Settings {
            get {
                return ResourceManager.GetString("Group_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Title:.
        /// </summary>
        public static string Group_Title_colon {
            get {
                return ResourceManager.GetString("Group_Title_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Color.
        /// </summary>
        public static string Hair_Color {
            get {
                return ResourceManager.GetString("Hair_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon ID.
        /// </summary>
        public static string Icon_ID {
            get {
                return ResourceManager.GetString("Icon_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Search.
        /// </summary>
        public static string Icon_Search {
            get {
                return ResourceManager.GetString("Icon_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import BMP.
        /// </summary>
        public static string Import_BMP {
            get {
                return ResourceManager.GetString("Import_BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import DDS.
        /// </summary>
        public static string Import_DDS {
            get {
                return ResourceManager.GetString("Import_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import From....
        /// </summary>
        public static string Import_From_dot {
            get {
                return ResourceManager.GetString("Import_From_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ModPack.
        /// </summary>
        public static string Import_ModPack {
            get {
                return ResourceManager.GetString("Import_ModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ModPack Wizard.
        /// </summary>
        public static string Import_ModPack_Wizard {
            get {
                return ResourceManager.GetString("Import_ModPack_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ModPacks.
        /// </summary>
        public static string Import_ModPacks {
            get {
                return ResourceManager.GetString("Import_ModPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included Mods in Option.
        /// </summary>
        public static string Included_Mods_in_Option {
            get {
                return ResourceManager.GetString("Included_Mods_in_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import while game is running..
        /// </summary>
        public static string Index_Locked {
            get {
                return ResourceManager.GetString("Index_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iris Color.
        /// </summary>
        public static string Iris_Color {
            get {
                return ResourceManager.GetString("Iris_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        public static string Item_List {
            get {
                return ResourceManager.GetString("Item_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us on Discord.
        /// </summary>
        public static string Join_us_on_Discord {
            get {
                return ResourceManager.GetString("Join_us_on_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Camera Position.
        /// </summary>
        public static string Keep_Camera_Position {
            get {
                return ResourceManager.GetString("Keep_Camera_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Of Detail.
        /// </summary>
        public static string Level_Of_Detail {
            get {
                return ResourceManager.GetString("Level_Of_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lights.
        /// </summary>
        public static string Lights {
            get {
                return ResourceManager.GetString("Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load From....
        /// </summary>
        public static string Load_From {
            get {
                return ResourceManager.GetString("Load_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Editor.
        /// </summary>
        public static string Material_Editor {
            get {
                return ResourceManager.GetString("Material_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Options.
        /// </summary>
        public static string Material_Options {
            get {
                return ResourceManager.GetString("Material_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh Data.
        /// </summary>
        public static string Mesh_Data {
            get {
                return ResourceManager.GetString("Mesh_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh Inspector.
        /// </summary>
        public static string Mesh_Inspector {
            get {
                return ResourceManager.GetString("Mesh_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh MetaData.
        /// </summary>
        public static string Mesh_MetaData {
            get {
                return ResourceManager.GetString("Mesh_MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No difference in mesh counts..
        /// </summary>
        public static string Mesh_No_Difference {
            get {
                return ResourceManager.GetString("Mesh_No_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh_Parts.
        /// </summary>
        public static string Mesh_Parts {
            get {
                return ResourceManager.GetString("Mesh_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No difference in mesh part counts for this mesh..
        /// </summary>
        public static string MeshPart_No_Difference {
            get {
                return ResourceManager.GetString("MeshPart_No_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Converter.
        /// </summary>
        public static string Mod_Converter {
            get {
                return ResourceManager.GetString("Mod_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Count:.
        /// </summary>
        public static string Mod_Count_colon {
            get {
                return ResourceManager.GetString("Mod_Count_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod List.
        /// </summary>
        public static string Mod_List {
            get {
                return ResourceManager.GetString("Mod_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Pack.
        /// </summary>
        public static string Mod_Pack {
            get {
                return ResourceManager.GetString("Mod_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Pack Author.
        /// </summary>
        public static string Mod_Pack_Author {
            get {
                return ResourceManager.GetString("Mod_Pack_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Pack Content.
        /// </summary>
        public static string Mod_Pack_Content {
            get {
                return ResourceManager.GetString("Mod_Pack_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Pack Directory.
        /// </summary>
        public static string Mod_Pack_Directory {
            get {
                return ResourceManager.GetString("Mod_Pack_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Pack General Info.
        /// </summary>
        public static string Mod_Pack_General_Info {
            get {
                return ResourceManager.GetString("Mod_Pack_General_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Pack Importer.
        /// </summary>
        public static string Mod_Pack_Importer {
            get {
                return ResourceManager.GetString("Mod_Pack_Importer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Pack Name.
        /// </summary>
        public static string Mod_Pack_Name {
            get {
                return ResourceManager.GetString("Mod_Pack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Repos.
        /// </summary>
        public static string Mod_Repos {
            get {
                return ResourceManager.GetString("Mod_Repos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modded Items.
        /// </summary>
        public static string Modded_Items {
            get {
                return ResourceManager.GetString("Modded_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model ID.
        /// </summary>
        public static string Model_ID {
            get {
                return ResourceManager.GetString("Model_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Inspector.
        /// </summary>
        public static string Model_Inspector {
            get {
                return ResourceManager.GetString("Model_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model MetaData.
        /// </summary>
        public static string Model_MetaData {
            get {
                return ResourceManager.GetString("Model_MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Options.
        /// </summary>
        public static string Model_Options {
            get {
                return ResourceManager.GetString("Model_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Search.
        /// </summary>
        public static string Model_Search {
            get {
                return ResourceManager.GetString("Model_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type.
        /// </summary>
        public static string Model_Type {
            get {
                return ResourceManager.GetString("Model_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Model ID....
        /// </summary>
        public static string ModelSearch_EnterID {
            get {
                return ResourceManager.GetString("ModelSearch_EnterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Items Found..
        /// </summary>
        public static string ModelSearch_ItemsFound {
            get {
                return ResourceManager.GetString("ModelSearch_ItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found..
        /// </summary>
        public static string ModelSearch_NoItemsFound {
            get {
                return ResourceManager.GetString("ModelSearch_NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number.
        /// </summary>
        public static string ModelSearch_Numeric {
            get {
                return ResourceManager.GetString("ModelSearch_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Model....
        /// </summary>
        public static string ModelStatus_Loading {
            get {
                return ResourceManager.GetString("ModelStatus_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Loaded Successfully.
        /// </summary>
        public static string ModelStatus_Success {
            get {
                return ResourceManager.GetString("ModelStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Updated Successfully.
        /// </summary>
        public static string ModelStatus_UpdateSuccess {
            get {
                return ResourceManager.GetString("ModelStatus_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModPack Wizard.
        /// </summary>
        public static string ModPack_Wizard {
            get {
                return ResourceManager.GetString("ModPack_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (e.g., This Mod Pack modifies blah blah blah, it replaces blah, and comes with several options for blah.).
        /// </summary>
        public static string ModPackDescription {
            get {
                return ResourceManager.GetString("ModPackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the general information for the Mod Pack you are creating..
        /// </summary>
        public static string ModPackGeneralInfo {
            get {
                return ResourceManager.GetString("ModPackGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string Mods {
            get {
                return ResourceManager.GetString("Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Options.
        /// </summary>
        public static string More_Options {
            get {
                return ResourceManager.GetString("More_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Selection.
        /// </summary>
        public static string Multi_Selection {
            get {
                return ResourceManager.GetString("Multi_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_colon {
            get {
                return ResourceManager.GetString("Name_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a new mesh containing {0} parts..
        /// </summary>
        public static string New_Mesh_MeshPart_Count {
            get {
                return ResourceManager.GetString("New_Mesh_MeshPart_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Page &gt;.
        /// </summary>
        public static string New_Page {
            get {
                return ResourceManager.GetString("New_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus Mods.
        /// </summary>
        public static string Nexus_Mods {
            get {
                return ResourceManager.GetString("Nexus_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no 3D Model mods present.
        ///
        ///If you would like to enable this, first import a model for the selected item..
        /// </summary>
        public static string No_3D_Mods {
            get {
                return ResourceManager.GetString("No_3D_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Material mods present.
        ///
        ///If you would like to enable this, first import a Material for the selected item..
        /// </summary>
        public static string No_Material_Mods {
            get {
                return ResourceManager.GetString("No_Material_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Texture mods present.
        ///
        ///If you would like to enable this, first import a texture for the selected item..
        /// </summary>
        public static string No_Texture_Mods {
            get {
                return ResourceManager.GetString("No_Texture_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num.
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mesh Inspector.
        /// </summary>
        public static string Open_Mesh_Inspector {
            get {
                return ResourceManager.GetString("Open_Mesh_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Description.
        /// </summary>
        public static string Option_Description {
            get {
                return ResourceManager.GetString("Option_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option List.
        /// </summary>
        public static string Option_List {
            get {
                return ResourceManager.GetString("Option_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Name.
        /// </summary>
        public static string Option_Name {
            get {
                return ResourceManager.GetString("Option_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Preview Image.
        /// </summary>
        public static string Option_Preview_Image {
            get {
                return ResourceManager.GetString("Option_Preview_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options List.
        /// </summary>
        public static string Options_List {
            get {
                return ResourceManager.GetString("Options_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Data.
        /// </summary>
        public static string Other_Data {
            get {
                return ResourceManager.GetString("Other_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Attributes.
        /// </summary>
        public static string Part_Attributes {
            get {
                return ResourceManager.GetString("Part_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Count.
        /// </summary>
        public static string Part_Count {
            get {
                return ResourceManager.GetString("Part_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Data.
        /// </summary>
        public static string Part_Data {
            get {
                return ResourceManager.GetString("Part_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        public static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrettyKitty Emporium.
        /// </summary>
        public static string PrettyKitty_Emporium {
            get {
                return ResourceManager.GetString("PrettyKitty_Emporium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview List.
        /// </summary>
        public static string Previe_List {
            get {
                return ResourceManager.GetString("Previe_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Previous Page.
        /// </summary>
        public static string Previous_Page {
            get {
                return ResourceManager.GetString("Previous_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Checker.
        /// </summary>
        public static string Problem_Checker {
            get {
                return ResourceManager.GetString("Problem_Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue checking Backup Index Files.
        /// </summary>
        public static string ProblemCheck_BackupError {
            get {
                return ResourceManager.GetString("ProblemCheck_BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Dat.....
        /// </summary>
        public static string ProblemCheck_Dat {
            get {
                return ResourceManager.GetString("ProblemCheck_Dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dat File ( 060000.win32.dat1 ) could not be found..
        /// </summary>
        public static string ProblemCheck_DatMissing {
            get {
                return ResourceManager.GetString("ProblemCheck_DatMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking For Empty Dat Files.....
        /// </summary>
        public static string ProblemCheck_DatSize {
            get {
                return ResourceManager.GetString("ProblemCheck_DatSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors found attempting to repair.....
        /// </summary>
        public static string ProblemCheck_ErrorsFound {
            get {
                return ResourceManager.GetString("ProblemCheck_ErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Dat files found, recommend Start Over.
        /// </summary>
        public static string ProblemCheck_ExtraDats {
            get {
                return ResourceManager.GetString("ProblemCheck_ExtraDats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Index Backups.....
        /// </summary>
        public static string ProblemCheck_IndexBackups {
            get {
                return ResourceManager.GetString("ProblemCheck_IndexBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Index Dat Values.....
        /// </summary>
        public static string ProblemCheck_IndexDat {
            get {
                return ResourceManager.GetString("ProblemCheck_IndexDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run repairs with game open. Please exit the game and run Check For Problems again..
        /// </summary>
        public static string ProblemCheck_IndexLocked {
            get {
                return ResourceManager.GetString("ProblemCheck_IndexLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Problem Check.....
        /// </summary>
        public static string ProblemCheck_Initialize {
            get {
                return ResourceManager.GetString("ProblemCheck_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking LoD settings.....
        /// </summary>
        public static string ProblemCheck_LoD {
            get {
                return ResourceManager.GetString("ProblemCheck_LoD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certain mods have issues with LoD ON..
        /// </summary>
        public static string ProblemCheck_LoDIssue {
            get {
                return ResourceManager.GetString("ProblemCheck_LoDIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning off LoD....
        /// </summary>
        public static string ProblemCheck_LoDOff {
            get {
                return ResourceManager.GetString("ProblemCheck_LoDOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoD OFF, running check....
        /// </summary>
        public static string ProblemCheck_LoDOffDone {
            get {
                return ResourceManager.GetString("ProblemCheck_LoDOffDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dat File ( 060000.win32.dat1 ) is missing data..
        /// </summary>
        public static string ProblemCheck_MissingData {
            get {
                return ResourceManager.GetString("ProblemCheck_MissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Modlist.....
        /// </summary>
        public static string ProblemCheck_ModList {
            get {
                return ResourceManager.GetString("ProblemCheck_ModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Offset was 0, Disable from File &gt; Modlist and reimport..
        /// </summary>
        public static string ProblemCheck_ModZero {
            get {
                return ResourceManager.GetString("ProblemCheck_ModZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Backup Found..
        /// </summary>
        public static string ProblemCheck_NoBackup {
            get {
                return ResourceManager.GetString("ProblemCheck_NoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries found in modlist..
        /// </summary>
        public static string ProblemCheck_NoEntries {
            get {
                return ResourceManager.GetString("ProblemCheck_NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Offset was 0, you will be unable to revert to original, consider starting over..
        /// </summary>
        public static string ProblemCheck_OriginalZero {
            get {
                return ResourceManager.GetString("ProblemCheck_OriginalZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index out of date..
        /// </summary>
        public static string ProblemCheck_OutOfDate {
            get {
                return ResourceManager.GetString("ProblemCheck_OutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairs Complete.
        /// </summary>
        public static string ProblemCheck_RepairComplete {
            get {
                return ResourceManager.GetString("ProblemCheck_RepairComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found unknown file type ( {0} ) offset is most likely corrupt..
        /// </summary>
        public static string ProblemCheck_UnkType {
            get {
                return ResourceManager.GetString("ProblemCheck_UnkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflection.
        /// </summary>
        public static string Reflection {
            get {
                return ResourceManager.GetString("Reflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Part Attribute.
        /// </summary>
        public static string Remove_Part_Attribute {
            get {
                return ResourceManager.GetString("Remove_Part_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed mesh(es)
        ///Removed Mesh Number(s):.
        /// </summary>
        public static string Removed_Mesh {
            get {
                return ResourceManager.GetString("Removed_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to these removed meshes above will have no effect.
        /// </summary>
        public static string Removed_Mesh_Note {
            get {
                return ResourceManager.GetString("Removed_Mesh_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed mesh part(s) for this mesh
        ///Removed Part Number(s):.
        /// </summary>
        public static string Removed_MeshParts {
            get {
                return ResourceManager.GetString("Removed_MeshParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to these removed parts below will have no effect.
        /// </summary>
        public static string Removed_MeshParts_Note {
            get {
                return ResourceManager.GetString("Removed_MeshParts_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bug.
        /// </summary>
        public static string Report_Bug {
            get {
                return ResourceManager.GetString("Report_Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string Reset_to_Default {
            get {
                return ResourceManager.GetString("Reset_to_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Directory.
        /// </summary>
        public static string Save_Directory {
            get {
                return ResourceManager.GetString("Save_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search_dot {
            get {
                return ResourceManager.GetString("Search_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file....
        /// </summary>
        public static string Select_a_file_dot {
            get {
                return ResourceManager.GetString("Select_a_file_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Active.
        /// </summary>
        public static string Select_Active {
            get {
                return ResourceManager.GetString("Select_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string Select_Language {
            get {
                return ResourceManager.GetString("Select_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mod.
        /// </summary>
        public static string Select_Mod {
            get {
                return ResourceManager.GetString("Select_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will disable all shape data for this meshes..
        /// </summary>
        public static string ShapeDescription1_line1 {
            get {
                return ResourceManager.GetString("ShapeDescription1_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is used when holes appear upon equipping other items.
        /// </summary>
        public static string ShapeDescription1_line2 {
            get {
                return ResourceManager.GetString("ShapeDescription1_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options for shape data will be available in a later version..
        /// </summary>
        public static string ShapeDescription1_line3 {
            get {
                return ResourceManager.GetString("ShapeDescription1_line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Shape Data for this mesh..
        /// </summary>
        public static string ShapeDescription2_line1 {
            get {
                return ResourceManager.GetString("ShapeDescription2_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options are disabled..
        /// </summary>
        public static string ShapeDescription2_line2 {
            get {
                return ResourceManager.GetString("ShapeDescription2_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        public static string Shapes {
            get {
                return ResourceManager.GetString("Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple ModPack.
        /// </summary>
        public static string Simple_ModPack {
            get {
                return ResourceManager.GetString("Simple_ModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple ModPack Creator.
        /// </summary>
        public static string Simple_ModPack_Creator {
            get {
                return ResourceManager.GetString("Simple_ModPack_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple ModPack Importer.
        /// </summary>
        public static string Simple_ModPack_Importer {
            get {
                return ResourceManager.GetString("Simple_ModPack_Importer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-Selection.
        /// </summary>
        public static string Single_Selection {
            get {
                return ResourceManager.GetString("Single_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string Size_colon {
            get {
                return ResourceManager.GetString("Size_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Color.
        /// </summary>
        public static string Skin_Color {
            get {
                return ResourceManager.GetString("Skin_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The Skin Color is mixed with the default skin color from the texture. All others are direct colors..
        /// </summary>
        public static string Skin_Color_Note_Info {
            get {
                return ResourceManager.GetString("Skin_Color_Note_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By:.
        /// </summary>
        public static string Sort_By_colon {
            get {
                return ResourceManager.GetString("Sort_By_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone (Non-ModPack).
        /// </summary>
        public static string Standalone_Non_ModPack {
            get {
                return ResourceManager.GetString("Standalone_Non_ModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string Start_Over {
            get {
                return ResourceManager.GetString("Start_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Model.
        /// </summary>
        public static string TD_Model {
            get {
                return ResourceManager.GetString("TD_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture.
        /// </summary>
        public static string Texture {
            get {
                return ResourceManager.GetString("Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Map.
        /// </summary>
        public static string Texture_Map {
            get {
                return ResourceManager.GetString("Texture_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Options.
        /// </summary>
        public static string Texture_Options {
            get {
                return ResourceManager.GetString("Texture_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures.
        /// </summary>
        public static string Textures {
            get {
                return ResourceManager.GetString("Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will only affect shared races.
        /// </summary>
        public static string This_will_only_affect_shared_races {
            get {
                return ResourceManager.GetString("This_will_only_affect_shared_races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translucency.
        /// </summary>
        public static string Translucency {
            get {
                return ResourceManager.GetString("Translucency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string Tutorials {
            get {
                return ResourceManager.GetString("Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found for icon {0}, try another..
        /// </summary>
        public static string UI_Search_NothingFound {
            get {
                return ResourceManager.GetString("UI_Search_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon values have a maximum of 6 digits, try again..
        /// </summary>
        public static string UI_SearchStatus_Max {
            get {
                return ResourceManager.GetString("UI_SearchStatus_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input can only be numbers, try again..
        /// </summary>
        public static string UI_SearchStatus_Numeric {
            get {
                return ResourceManager.GetString("UI_SearchStatus_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update TEX.
        /// </summary>
        public static string Update_TEX {
            get {
                return ResourceManager.GetString("Update_TEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Currently Modded Item.
        /// </summary>
        public static string Use_Currently_Modded_Item {
            get {
                return ResourceManager.GetString("Use_Currently_Modded_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        public static string Variant {
            get {
                return ResourceManager.GetString("Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version_colon {
            get {
                return ResourceManager.GetString("Version_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Colors.
        /// </summary>
        public static string Vertex_Colors {
            get {
                return ResourceManager.GetString("Vertex_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Data Structure.
        /// </summary>
        public static string Vertex_Data_Structure {
            get {
                return ResourceManager.GetString("Vertex_Data_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Github Repo.
        /// </summary>
        public static string View_Github_Repo {
            get {
                return ResourceManager.GetString("View_Github_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer Options.
        /// </summary>
        public static string Viewer_Options {
            get {
                return ResourceManager.GetString("Viewer_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Website.
        /// </summary>
        public static string Visit_Website {
            get {
                return ResourceManager.GetString("Visit_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XIV Mod Archive.
        /// </summary>
        public static string XIV_Mod_Archive {
            get {
                return ResourceManager.GetString("XIV_Mod_Archive", resourceCulture);
            }
        }
    }
}
