//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About TexTools 的本地化字符串。
        /// </summary>
        public static string About_TexTools {
            get {
                return ResourceManager.GetString("About_TexTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a Model using advanced options 的本地化字符串。
        /// </summary>
        public static string Add_a_Model_using_advanced_options {
            get {
                return ResourceManager.GetString("Add_a_Model_using_advanced_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Group 的本地化字符串。
        /// </summary>
        public static string Add_Group {
            get {
                return ResourceManager.GetString("Add_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Texture Part 的本地化字符串。
        /// </summary>
        public static string Add_NewTexturePart {
            get {
                return ResourceManager.GetString("Add_NewTexturePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add/Remove 的本地化字符串。
        /// </summary>
        public static string Add_Remove {
            get {
                return ResourceManager.GetString("Add_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add To Part Attribute 的本地化字符串。
        /// </summary>
        public static string Add_To_Part_Attribute {
            get {
                return ResourceManager.GetString("Add_To_Part_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add w/ Adv. Options 的本地化字符串。
        /// </summary>
        public static string Add_w_Adv_Options {
            get {
                return ResourceManager.GetString("Add_w_Adv_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 added mesh(es)
        ///Change material for new mesh(es) if necessary. 的本地化字符串。
        /// </summary>
        public static string Added_Mesh {
            get {
                return ResourceManager.GetString("Added_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 added mesh part(s) for this mesh
        ///Change attributes for new part(s) below if necessary 的本地化字符串。
        /// </summary>
        public static string Added_MeshParts {
            get {
                return ResourceManager.GetString("Added_MeshParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Import 的本地化字符串。
        /// </summary>
        public static string Advanced_Import {
            get {
                return ResourceManager.GetString("Advanced_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Model Import 的本地化字符串。
        /// </summary>
        public static string Advanced_Model_Import {
            get {
                return ResourceManager.GetString("Advanced_Model_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Model Options 的本地化字符串。
        /// </summary>
        public static string Advanced_Model_Options {
            get {
                return ResourceManager.GetString("Advanced_Model_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attributes 的本地化字符串。
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: 的本地化字符串。
        /// </summary>
        public static string Author_colon {
            get {
                return ResourceManager.GetString("Author_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available Attributes 的本地化字符串。
        /// </summary>
        public static string Available_Attributes {
            get {
                return ResourceManager.GetString("Available_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Index Files 的本地化字符串。
        /// </summary>
        public static string Backup_Index_Files {
            get {
                return ResourceManager.GetString("Backup_Index_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backups Directory 的本地化字符串。
        /// </summary>
        public static string Backups_Directory {
            get {
                return ResourceManager.GetString("Backups_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch 的本地化字符串。
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BG Color 的本地化字符串。
        /// </summary>
        public static string BG_Color {
            get {
                return ResourceManager.GetString("BG_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body 的本地化字符串。
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bone addition is automatic 的本地化字符串。
        /// </summary>
        public static string Bone_addition_is_automatic {
            get {
                return ResourceManager.GetString("Bone_addition_is_automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bones 的本地化字符串。
        /// </summary>
        public static string Bones {
            get {
                return ResourceManager.GetString("Bones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check For Problems 的本地化字符串。
        /// </summary>
        public static string Check_For_Problems {
            get {
                return ResourceManager.GetString("Check_For_Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 China Discord 的本地化字符串。
        /// </summary>
        public static string ChinaDiscord {
            get {
                return ResourceManager.GetString("ChinaDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Selected 的本地化字符串。
        /// </summary>
        public static string Clear_Selected {
            get {
                return ResourceManager.GetString("Clear_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to add a preview image 的本地化字符串。
        /// </summary>
        public static string Clic_here_to_add_a_preview_image {
            get {
                return ResourceManager.GetString("Clic_here_to_add_a_preview_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Colors &amp;amp; Skins 的本地化字符串。
        /// </summary>
        public static string Colors_Skins {
            get {
                return ResourceManager.GetString("Colors_Skins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count: 的本地化字符串。
        /// </summary>
        public static string Count_colon {
            get {
                return ResourceManager.GetString("Count_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Modpack 的本地化字符串。
        /// </summary>
        public static string Create_Modpack {
            get {
                return ResourceManager.GetString("Create_Modpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create ModPack Wizard 的本地化字符串。
        /// </summary>
        public static string Create_ModPack_Wizard {
            get {
                return ResourceManager.GetString("Create_ModPack_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cull Mode 的本地化字符串。
        /// </summary>
        public static string Cull_Mode {
            get {
                return ResourceManager.GetString("Cull_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Language: 的本地化字符串。
        /// </summary>
        public static string Current_Language_colon {
            get {
                return ResourceManager.GetString("Current_Language_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize 的本地化字符串。
        /// </summary>
        public static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TexTools will choose the selected race by default if available when viewing Textures and Models. 的本地化字符串。
        /// </summary>
        public static string Customize_DefaultRace {
            get {
                return ResourceManager.GetString("Customize_DefaultRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DAE file to import 的本地化字符串。
        /// </summary>
        public static string DAE_file_to_import {
            get {
                return ResourceManager.GetString("DAE_file_to_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DAE Info 的本地化字符串。
        /// </summary>
        public static string DAE_Info {
            get {
                return ResourceManager.GetString("DAE_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Skin 的本地化字符串。
        /// </summary>
        public static string Default_Skin {
            get {
                return ResourceManager.GetString("Default_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directories 的本地化字符串。
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable All Mods 的本地化字符串。
        /// </summary>
        public static string Disable_All_Mods {
            get {
                return ResourceManager.GetString("Disable_All_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Shape Data 的本地化字符串。
        /// </summary>
        public static string Disable_Shape_Data {
            get {
                return ResourceManager.GetString("Disable_Shape_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Group 的本地化字符串。
        /// </summary>
        public static string Edit_Group {
            get {
                return ResourceManager.GetString("Edit_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable All Mods 的本地化字符串。
        /// </summary>
        public static string Enable_All_Mods {
            get {
                return ResourceManager.GetString("Enable_All_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable/Disable 的本地化字符串。
        /// </summary>
        public static string Enable_Disable {
            get {
                return ResourceManager.GetString("Enable_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a brief description of your Mod Pack. 的本地化字符串。
        /// </summary>
        public static string Enter_a_brief_description_of_your_Mod_Pack {
            get {
                return ResourceManager.GetString("Enter_a_brief_description_of_your_Mod_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a description for the selected option here... 的本地化字符串。
        /// </summary>
        public static string Enter_a_description_for_the_selected_option_here_dot {
            get {
                return ResourceManager.GetString("Enter_a_description_for_the_selected_option_here_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a Model ID... 的本地化字符串。
        /// </summary>
        public static string Enter_a_Model_ID_dot {
            get {
                return ResourceManager.GetString("Enter_a_Model_ID_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a Name for the Group here 的本地化字符串。
        /// </summary>
        public static string Enter_a_Name_for_the_Group_here {
            get {
                return ResourceManager.GetString("Enter_a_Name_for_the_Group_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Etc Color 的本地化字符串。
        /// </summary>
        public static string Etc_Color {
            get {
                return ResourceManager.GetString("Etc_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export BMP 的本地化字符串。
        /// </summary>
        public static string Export_BMP {
            get {
                return ResourceManager.GetString("Export_BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Both 的本地化字符串。
        /// </summary>
        public static string Export_Both {
            get {
                return ResourceManager.GetString("Export_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export DAE file 的本地化字符串。
        /// </summary>
        public static string Export_DAE_file {
            get {
                return ResourceManager.GetString("Export_DAE_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export DAE + Materials 的本地化字符串。
        /// </summary>
        public static string Export_DAE_Materials {
            get {
                return ResourceManager.GetString("Export_DAE_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export DDS 的本地化字符串。
        /// </summary>
        public static string Export_DDS {
            get {
                return ResourceManager.GetString("Export_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export OBJ files 的本地化字符串。
        /// </summary>
        public static string Export_OBJ_files {
            get {
                return ResourceManager.GetString("Export_OBJ_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Settings 的本地化字符串。
        /// </summary>
        public static string Export_Settings {
            get {
                return ResourceManager.GetString("Export_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFXIV Directory 的本地化字符串。
        /// </summary>
        public static string FFXIV_Directory {
            get {
                return ResourceManager.GetString("FFXIV_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter By: 的本地化字符串。
        /// </summary>
        public static string Filter_By_colon {
            get {
                return ResourceManager.GetString("Filter_By_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finalizing... 的本地化字符串。
        /// </summary>
        public static string Finalizing {
            get {
                return ResourceManager.GetString("Finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Alpha 的本地化字符串。
        /// </summary>
        public static string Flip_Alpha {
            get {
                return ResourceManager.GetString("Flip_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (For Translucency or ColorSet) 的本地化字符串。
        /// </summary>
        public static string For_Translucency_or_ColorSet {
            get {
                return ResourceManager.GetString("For_Translucency_or_ColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go through the wizard and select relevant options to import mod pack 的本地化字符串。
        /// </summary>
        public static string Go_through_the_wizard_and_select_relevant_options_to_import_mod_pack {
            get {
                return ResourceManager.GetString("Go_through_the_wizard_and_select_relevant_options_to_import_mod_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Options 的本地化字符串。
        /// </summary>
        public static string Group_Options {
            get {
                return ResourceManager.GetString("Group_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Settings 的本地化字符串。
        /// </summary>
        public static string Group_Settings {
            get {
                return ResourceManager.GetString("Group_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Title: 的本地化字符串。
        /// </summary>
        public static string Group_Title_colon {
            get {
                return ResourceManager.GetString("Group_Title_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hair Color 的本地化字符串。
        /// </summary>
        public static string Hair_Color {
            get {
                return ResourceManager.GetString("Hair_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon ID 的本地化字符串。
        /// </summary>
        public static string Icon_ID {
            get {
                return ResourceManager.GetString("Icon_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon Search 的本地化字符串。
        /// </summary>
        public static string Icon_Search {
            get {
                return ResourceManager.GetString("Icon_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import BMP 的本地化字符串。
        /// </summary>
        public static string Import_BMP {
            get {
                return ResourceManager.GetString("Import_BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import DDS 的本地化字符串。
        /// </summary>
        public static string Import_DDS {
            get {
                return ResourceManager.GetString("Import_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import From... 的本地化字符串。
        /// </summary>
        public static string Import_From_dot {
            get {
                return ResourceManager.GetString("Import_From_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import ModPack 的本地化字符串。
        /// </summary>
        public static string Import_ModPack {
            get {
                return ResourceManager.GetString("Import_ModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import ModPack Wizard 的本地化字符串。
        /// </summary>
        public static string Import_ModPack_Wizard {
            get {
                return ResourceManager.GetString("Import_ModPack_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import ModPacks 的本地化字符串。
        /// </summary>
        public static string Import_ModPacks {
            get {
                return ResourceManager.GetString("Import_ModPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Included Mods in Option 的本地化字符串。
        /// </summary>
        public static string Included_Mods_in_Option {
            get {
                return ResourceManager.GetString("Included_Mods_in_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to import while game is running. 的本地化字符串。
        /// </summary>
        public static string Index_Locked {
            get {
                return ResourceManager.GetString("Index_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Iris Color 的本地化字符串。
        /// </summary>
        public static string Iris_Color {
            get {
                return ResourceManager.GetString("Iris_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item List 的本地化字符串。
        /// </summary>
        public static string Item_List {
            get {
                return ResourceManager.GetString("Item_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Join us on Discord 的本地化字符串。
        /// </summary>
        public static string Join_us_on_Discord {
            get {
                return ResourceManager.GetString("Join_us_on_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Camera Position 的本地化字符串。
        /// </summary>
        public static string Keep_Camera_Position {
            get {
                return ResourceManager.GetString("Keep_Camera_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level Of Detail 的本地化字符串。
        /// </summary>
        public static string Level_Of_Detail {
            get {
                return ResourceManager.GetString("Level_Of_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lights 的本地化字符串。
        /// </summary>
        public static string Lights {
            get {
                return ResourceManager.GetString("Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map 的本地化字符串。
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material 的本地化字符串。
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material Options 的本地化字符串。
        /// </summary>
        public static string Material_Options {
            get {
                return ResourceManager.GetString("Material_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Materials 的本地化字符串。
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mesh Data 的本地化字符串。
        /// </summary>
        public static string Mesh_Data {
            get {
                return ResourceManager.GetString("Mesh_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mesh Inspector 的本地化字符串。
        /// </summary>
        public static string Mesh_Inspector {
            get {
                return ResourceManager.GetString("Mesh_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mesh MetaData 的本地化字符串。
        /// </summary>
        public static string Mesh_MetaData {
            get {
                return ResourceManager.GetString("Mesh_MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No difference in mesh counts. 的本地化字符串。
        /// </summary>
        public static string Mesh_No_Difference {
            get {
                return ResourceManager.GetString("Mesh_No_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mesh_Parts 的本地化字符串。
        /// </summary>
        public static string Mesh_Parts {
            get {
                return ResourceManager.GetString("Mesh_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No difference in mesh part counts for this mesh. 的本地化字符串。
        /// </summary>
        public static string MeshPart_No_Difference {
            get {
                return ResourceManager.GetString("MeshPart_No_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Count: 的本地化字符串。
        /// </summary>
        public static string Mod_Count_colon {
            get {
                return ResourceManager.GetString("Mod_Count_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod List 的本地化字符串。
        /// </summary>
        public static string Mod_List {
            get {
                return ResourceManager.GetString("Mod_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Pack 的本地化字符串。
        /// </summary>
        public static string Mod_Pack {
            get {
                return ResourceManager.GetString("Mod_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Pack Author 的本地化字符串。
        /// </summary>
        public static string Mod_Pack_Author {
            get {
                return ResourceManager.GetString("Mod_Pack_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Pack Content 的本地化字符串。
        /// </summary>
        public static string Mod_Pack_Content {
            get {
                return ResourceManager.GetString("Mod_Pack_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Pack Directory 的本地化字符串。
        /// </summary>
        public static string Mod_Pack_Directory {
            get {
                return ResourceManager.GetString("Mod_Pack_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Pack General Info 的本地化字符串。
        /// </summary>
        public static string Mod_Pack_General_Info {
            get {
                return ResourceManager.GetString("Mod_Pack_General_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Pack Importer 的本地化字符串。
        /// </summary>
        public static string Mod_Pack_Importer {
            get {
                return ResourceManager.GetString("Mod_Pack_Importer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Pack Name 的本地化字符串。
        /// </summary>
        public static string Mod_Pack_Name {
            get {
                return ResourceManager.GetString("Mod_Pack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Repos 的本地化字符串。
        /// </summary>
        public static string Mod_Repos {
            get {
                return ResourceManager.GetString("Mod_Repos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modded Items 的本地化字符串。
        /// </summary>
        public static string Modded_Items {
            get {
                return ResourceManager.GetString("Modded_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model ID 的本地化字符串。
        /// </summary>
        public static string Model_ID {
            get {
                return ResourceManager.GetString("Model_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Inspector 的本地化字符串。
        /// </summary>
        public static string Model_Inspector {
            get {
                return ResourceManager.GetString("Model_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model MetaData 的本地化字符串。
        /// </summary>
        public static string Model_MetaData {
            get {
                return ResourceManager.GetString("Model_MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Options 的本地化字符串。
        /// </summary>
        public static string Model_Options {
            get {
                return ResourceManager.GetString("Model_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Search 的本地化字符串。
        /// </summary>
        public static string Model_Search {
            get {
                return ResourceManager.GetString("Model_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Type 的本地化字符串。
        /// </summary>
        public static string Model_Type {
            get {
                return ResourceManager.GetString("Model_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a Model ID... 的本地化字符串。
        /// </summary>
        public static string ModelSearch_EnterID {
            get {
                return ResourceManager.GetString("ModelSearch_EnterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Items Found. 的本地化字符串。
        /// </summary>
        public static string ModelSearch_ItemsFound {
            get {
                return ResourceManager.GetString("ModelSearch_ItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Items Found. 的本地化字符串。
        /// </summary>
        public static string ModelSearch_NoItemsFound {
            get {
                return ResourceManager.GetString("ModelSearch_NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must be a number 的本地化字符串。
        /// </summary>
        public static string ModelSearch_Numeric {
            get {
                return ResourceManager.GetString("ModelSearch_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading Model... 的本地化字符串。
        /// </summary>
        public static string ModelStatus_Loading {
            get {
                return ResourceManager.GetString("ModelStatus_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Loaded Successfully 的本地化字符串。
        /// </summary>
        public static string ModelStatus_Success {
            get {
                return ResourceManager.GetString("ModelStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Updated Successfully 的本地化字符串。
        /// </summary>
        public static string ModelStatus_UpdateSuccess {
            get {
                return ResourceManager.GetString("ModelStatus_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModPack Wizard 的本地化字符串。
        /// </summary>
        public static string ModPack_Wizard {
            get {
                return ResourceManager.GetString("ModPack_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (e.g., This Mod Pack modifies blah blah blah, it replaces blah, and comes with several options for blah.) 的本地化字符串。
        /// </summary>
        public static string ModPackDescription {
            get {
                return ResourceManager.GetString("ModPackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill out the general information for the Mod Pack you are creating. 的本地化字符串。
        /// </summary>
        public static string ModPackGeneralInfo {
            get {
                return ResourceManager.GetString("ModPackGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mods 的本地化字符串。
        /// </summary>
        public static string Mods {
            get {
                return ResourceManager.GetString("Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More Options 的本地化字符串。
        /// </summary>
        public static string More_Options {
            get {
                return ResourceManager.GetString("More_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi-Selection 的本地化字符串。
        /// </summary>
        public static string Multi_Selection {
            get {
                return ResourceManager.GetString("Multi_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        public static string Name_colon {
            get {
                return ResourceManager.GetString("Name_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a new mesh containing {0} parts. 的本地化字符串。
        /// </summary>
        public static string New_Mesh_MeshPart_Count {
            get {
                return ResourceManager.GetString("New_Mesh_MeshPart_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Page &gt; 的本地化字符串。
        /// </summary>
        public static string New_Page {
            get {
                return ResourceManager.GetString("New_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nexus Mods 的本地化字符串。
        /// </summary>
        public static string Nexus_Mods {
            get {
                return ResourceManager.GetString("Nexus_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no 3D Model mods present.
        ///
        ///If you would like to enable this, first import a model for the selected item. 的本地化字符串。
        /// </summary>
        public static string No_3D_Mods {
            get {
                return ResourceManager.GetString("No_3D_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no Material mods present.
        ///
        ///If you would like to enable this, first import a Material for the selected item. 的本地化字符串。
        /// </summary>
        public static string No_Material_Mods {
            get {
                return ResourceManager.GetString("No_Material_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no Texture mods present.
        ///
        ///If you would like to enable this, first import a texture for the selected item. 的本地化字符串。
        /// </summary>
        public static string No_Texture_Mods {
            get {
                return ResourceManager.GetString("No_Texture_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Num 的本地化字符串。
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Mesh Inspector 的本地化字符串。
        /// </summary>
        public static string Open_Mesh_Inspector {
            get {
                return ResourceManager.GetString("Open_Mesh_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option Description 的本地化字符串。
        /// </summary>
        public static string Option_Description {
            get {
                return ResourceManager.GetString("Option_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option List 的本地化字符串。
        /// </summary>
        public static string Option_List {
            get {
                return ResourceManager.GetString("Option_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option Name 的本地化字符串。
        /// </summary>
        public static string Option_Name {
            get {
                return ResourceManager.GetString("Option_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option Preview Image 的本地化字符串。
        /// </summary>
        public static string Option_Preview_Image {
            get {
                return ResourceManager.GetString("Option_Preview_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options List 的本地化字符串。
        /// </summary>
        public static string Options_List {
            get {
                return ResourceManager.GetString("Options_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Data 的本地化字符串。
        /// </summary>
        public static string Other_Data {
            get {
                return ResourceManager.GetString("Other_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part 的本地化字符串。
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part Attributes 的本地化字符串。
        /// </summary>
        public static string Part_Attributes {
            get {
                return ResourceManager.GetString("Part_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part Count 的本地化字符串。
        /// </summary>
        public static string Part_Count {
            get {
                return ResourceManager.GetString("Part_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part Data 的本地化字符串。
        /// </summary>
        public static string Part_Data {
            get {
                return ResourceManager.GetString("Part_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paths 的本地化字符串。
        /// </summary>
        public static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrettyKitty Emporium 的本地化字符串。
        /// </summary>
        public static string PrettyKitty_Emporium {
            get {
                return ResourceManager.GetString("PrettyKitty_Emporium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview List 的本地化字符串。
        /// </summary>
        public static string Previe_List {
            get {
                return ResourceManager.GetString("Previe_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt; Previous Page 的本地化字符串。
        /// </summary>
        public static string Previous_Page {
            get {
                return ResourceManager.GetString("Previous_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Problem Checker 的本地化字符串。
        /// </summary>
        public static string Problem_Checker {
            get {
                return ResourceManager.GetString("Problem_Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an issue checking Backup Index Files 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_BackupError {
            get {
                return ResourceManager.GetString("ProblemCheck_BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking Dat.... 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_Dat {
            get {
                return ResourceManager.GetString("ProblemCheck_Dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Dat File ( 060000.win32.dat1 ) could not be found. 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_DatMissing {
            get {
                return ResourceManager.GetString("ProblemCheck_DatMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking For Empty Dat Files.... 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_DatSize {
            get {
                return ResourceManager.GetString("ProblemCheck_DatSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Errors found attempting to repair.... 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_ErrorsFound {
            get {
                return ResourceManager.GetString("ProblemCheck_ErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Dat files found, recommend Start Over 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_ExtraDats {
            get {
                return ResourceManager.GetString("ProblemCheck_ExtraDats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking Index Backups.... 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_IndexBackups {
            get {
                return ResourceManager.GetString("ProblemCheck_IndexBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking Index Dat Values.... 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_IndexDat {
            get {
                return ResourceManager.GetString("ProblemCheck_IndexDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot run repairs with game open. Please exit the game and run Check For Problems again. 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_IndexLocked {
            get {
                return ResourceManager.GetString("ProblemCheck_IndexLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing Problem Check.... 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_Initialize {
            get {
                return ResourceManager.GetString("ProblemCheck_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking LoD settings.... 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_LoD {
            get {
                return ResourceManager.GetString("ProblemCheck_LoD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certain mods have issues with LoD ON. 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_LoDIssue {
            get {
                return ResourceManager.GetString("ProblemCheck_LoDIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turning off LoD... 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_LoDOff {
            get {
                return ResourceManager.GetString("ProblemCheck_LoDOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoD OFF, running check... 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_LoDOffDone {
            get {
                return ResourceManager.GetString("ProblemCheck_LoDOffDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Dat File ( 060000.win32.dat1 ) is missing data. 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_MissingData {
            get {
                return ResourceManager.GetString("ProblemCheck_MissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking Modlist.... 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_ModList {
            get {
                return ResourceManager.GetString("ProblemCheck_ModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Offset was 0, Disable from File &gt; Modlist and reimport. 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_ModZero {
            get {
                return ResourceManager.GetString("ProblemCheck_ModZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Backup Found. 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_NoBackup {
            get {
                return ResourceManager.GetString("ProblemCheck_NoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No entries found in modlist. 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_NoEntries {
            get {
                return ResourceManager.GetString("ProblemCheck_NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Offset was 0, you will be unable to revert to original, consider starting over. 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_OriginalZero {
            get {
                return ResourceManager.GetString("ProblemCheck_OriginalZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 index out of date. 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_OutOfDate {
            get {
                return ResourceManager.GetString("ProblemCheck_OutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repairs Complete 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_RepairComplete {
            get {
                return ResourceManager.GetString("ProblemCheck_RepairComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found unknown file type ( {0} ) offset is most likely corrupt. 的本地化字符串。
        /// </summary>
        public static string ProblemCheck_UnkType {
            get {
                return ResourceManager.GetString("ProblemCheck_UnkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Race 的本地化字符串。
        /// </summary>
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reflection 的本地化字符串。
        /// </summary>
        public static string Reflection {
            get {
                return ResourceManager.GetString("Reflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Part Attribute 的本地化字符串。
        /// </summary>
        public static string Remove_Part_Attribute {
            get {
                return ResourceManager.GetString("Remove_Part_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 removed mesh(es)
        ///Removed Mesh Number(s): 的本地化字符串。
        /// </summary>
        public static string Removed_Mesh {
            get {
                return ResourceManager.GetString("Removed_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes to these removed meshes above will have no effect 的本地化字符串。
        /// </summary>
        public static string Removed_Mesh_Note {
            get {
                return ResourceManager.GetString("Removed_Mesh_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 removed mesh part(s) for this mesh
        ///Removed Part Number(s): 的本地化字符串。
        /// </summary>
        public static string Removed_MeshParts {
            get {
                return ResourceManager.GetString("Removed_MeshParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes to these removed parts below will have no effect 的本地化字符串。
        /// </summary>
        public static string Removed_MeshParts_Note {
            get {
                return ResourceManager.GetString("Removed_MeshParts_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Bug 的本地化字符串。
        /// </summary>
        public static string Report_Bug {
            get {
                return ResourceManager.GetString("Report_Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to Default 的本地化字符串。
        /// </summary>
        public static string Reset_to_Default {
            get {
                return ResourceManager.GetString("Reset_to_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Directory 的本地化字符串。
        /// </summary>
        public static string Save_Directory {
            get {
                return ResourceManager.GetString("Save_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search... 的本地化字符串。
        /// </summary>
        public static string Search_dot {
            get {
                return ResourceManager.GetString("Search_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a file... 的本地化字符串。
        /// </summary>
        public static string Select_a_file_dot {
            get {
                return ResourceManager.GetString("Select_a_file_dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Active 的本地化字符串。
        /// </summary>
        public static string Select_Active {
            get {
                return ResourceManager.GetString("Select_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        public static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Language 的本地化字符串。
        /// </summary>
        public static string Select_Language {
            get {
                return ResourceManager.GetString("Select_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Mod 的本地化字符串。
        /// </summary>
        public static string Select_Mod {
            get {
                return ResourceManager.GetString("Select_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will disable all shape data for this meshes. 的本地化字符串。
        /// </summary>
        public static string ShapeDescription1_line1 {
            get {
                return ResourceManager.GetString("ShapeDescription1_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This option is used when holes appear upon equipping other items 的本地化字符串。
        /// </summary>
        public static string ShapeDescription1_line2 {
            get {
                return ResourceManager.GetString("ShapeDescription1_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More options for shape data will be available in a later version. 的本地化字符串。
        /// </summary>
        public static string ShapeDescription1_line3 {
            get {
                return ResourceManager.GetString("ShapeDescription1_line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no Shape Data for this mesh. 的本地化字符串。
        /// </summary>
        public static string ShapeDescription2_line1 {
            get {
                return ResourceManager.GetString("ShapeDescription2_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options are disabled. 的本地化字符串。
        /// </summary>
        public static string ShapeDescription2_line2 {
            get {
                return ResourceManager.GetString("ShapeDescription2_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shapes 的本地化字符串。
        /// </summary>
        public static string Shapes {
            get {
                return ResourceManager.GetString("Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple ModPack 的本地化字符串。
        /// </summary>
        public static string Simple_ModPack {
            get {
                return ResourceManager.GetString("Simple_ModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple ModPack Creator 的本地化字符串。
        /// </summary>
        public static string Simple_ModPack_Creator {
            get {
                return ResourceManager.GetString("Simple_ModPack_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple ModPack Importer 的本地化字符串。
        /// </summary>
        public static string Simple_ModPack_Importer {
            get {
                return ResourceManager.GetString("Simple_ModPack_Importer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single-Selection 的本地化字符串。
        /// </summary>
        public static string Single_Selection {
            get {
                return ResourceManager.GetString("Single_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size: 的本地化字符串。
        /// </summary>
        public static string Size_colon {
            get {
                return ResourceManager.GetString("Size_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skin Color 的本地化字符串。
        /// </summary>
        public static string Skin_Color {
            get {
                return ResourceManager.GetString("Skin_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: The Skin Color is mixed with the default skin color from the texture. All others are direct colors. 的本地化字符串。
        /// </summary>
        public static string Skin_Color_Note_Info {
            get {
                return ResourceManager.GetString("Skin_Color_Note_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slot 的本地化字符串。
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standalone (Non-ModPack) 的本地化字符串。
        /// </summary>
        public static string Standalone_Non_ModPack {
            get {
                return ResourceManager.GetString("Standalone_Non_ModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Over 的本地化字符串。
        /// </summary>
        public static string Start_Over {
            get {
                return ResourceManager.GetString("Start_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D Model 的本地化字符串。
        /// </summary>
        public static string TD_Model {
            get {
                return ResourceManager.GetString("TD_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture 的本地化字符串。
        /// </summary>
        public static string Texture {
            get {
                return ResourceManager.GetString("Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture Map 的本地化字符串。
        /// </summary>
        public static string Texture_Map {
            get {
                return ResourceManager.GetString("Texture_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture Options 的本地化字符串。
        /// </summary>
        public static string Texture_Options {
            get {
                return ResourceManager.GetString("Texture_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textures 的本地化字符串。
        /// </summary>
        public static string Textures {
            get {
                return ResourceManager.GetString("Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will only affect shared races 的本地化字符串。
        /// </summary>
        public static string This_will_only_affect_shared_races {
            get {
                return ResourceManager.GetString("This_will_only_affect_shared_races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translucency 的本地化字符串。
        /// </summary>
        public static string Translucency {
            get {
                return ResourceManager.GetString("Translucency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tutorials 的本地化字符串。
        /// </summary>
        public static string Tutorials {
            get {
                return ResourceManager.GetString("Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data found for icon {0}, try another. 的本地化字符串。
        /// </summary>
        public static string UI_Search_NothingFound {
            get {
                return ResourceManager.GetString("UI_Search_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon values have a maximum of 6 digits, try again. 的本地化字符串。
        /// </summary>
        public static string UI_SearchStatus_Max {
            get {
                return ResourceManager.GetString("UI_SearchStatus_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input can only be numbers, try again. 的本地化字符串。
        /// </summary>
        public static string UI_SearchStatus_Numeric {
            get {
                return ResourceManager.GetString("UI_SearchStatus_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update TEX 的本地化字符串。
        /// </summary>
        public static string Update_TEX {
            get {
                return ResourceManager.GetString("Update_TEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Currently Modded Item 的本地化字符串。
        /// </summary>
        public static string Use_Currently_Modded_Item {
            get {
                return ResourceManager.GetString("Use_Currently_Modded_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variant 的本地化字符串。
        /// </summary>
        public static string Variant {
            get {
                return ResourceManager.GetString("Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string Version_colon {
            get {
                return ResourceManager.GetString("Version_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertex Colors 的本地化字符串。
        /// </summary>
        public static string Vertex_Colors {
            get {
                return ResourceManager.GetString("Vertex_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertex Data Structure 的本地化字符串。
        /// </summary>
        public static string Vertex_Data_Structure {
            get {
                return ResourceManager.GetString("Vertex_Data_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Github Repo 的本地化字符串。
        /// </summary>
        public static string View_Github_Repo {
            get {
                return ResourceManager.GetString("View_Github_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Viewer Options 的本地化字符串。
        /// </summary>
        public static string Viewer_Options {
            get {
                return ResourceManager.GetString("Viewer_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit Website 的本地化字符串。
        /// </summary>
        public static string Visit_Website {
            get {
                return ResourceManager.GetString("Visit_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XIV Mod Archive 的本地化字符串。
        /// </summary>
        public static string XIV_Mod_Archive {
            get {
                return ResourceManager.GetString("XIV_Mod_Archive", resourceCulture);
            }
        }
    }
}
