//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebUrl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebUrl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools.Resources.WebUrl", typeof(WebUrl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://project.dualwield.net/bug_report_page.php.
        /// </summary>
        internal static string BugReport_Website {
            get {
                return ResourceManager.GetString("BugReport_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.gg/jKPqnhk.
        /// </summary>
        internal static string Discord_China {
            get {
                return ResourceManager.GetString("Discord_China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.gg/ffxivtextools.
        /// </summary>
        internal static string Discord_Invite {
            get {
                return ResourceManager.GetString("Discord_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=B78KX56JPQFMJ&amp;source=url.
        /// </summary>
        internal static string Donate_Website {
            get {
                return ResourceManager.GetString("Donate_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://textools.dualwield.net/donate/.
        /// </summary>
        internal static string FFXIV_Donate {
            get {
                return ResourceManager.GetString("FFXIV_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/textools/.
        /// </summary>
        internal static string Github_Website {
            get {
                return ResourceManager.GetString("Github_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.nexusmods.com/finalfantasy14.
        /// </summary>
        internal static string NexusMods_Website {
            get {
                return ResourceManager.GetString("NexusMods_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://prettykittyemporium.blogspot.com/.
        /// </summary>
        internal static string PKEmporium_Website {
            get {
                return ResourceManager.GetString("PKEmporium_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/TexTools/FFXIV_TexTools_Updater/master/updater_beta.xml.
        /// </summary>
        internal static string TexTools_Beta_Update_Url {
            get {
                return ResourceManager.GetString("TexTools_Beta_Update_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/TexTools/FFXIV_TexTools_Updater/master/updater.xml.
        /// </summary>
        internal static string TexTools_Update_Url {
            get {
                return ResourceManager.GetString("TexTools_Update_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://textools.dualwield.net/.
        /// </summary>
        internal static string TexTools_Website {
            get {
                return ResourceManager.GetString("TexTools_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://textools.dualwield.net/tutorials/.
        /// </summary>
        internal static string Tutorials_Website {
            get {
                return ResourceManager.GetString("Tutorials_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.xivmodarchive.com/.
        /// </summary>
        internal static string XivModArchive_Website {
            get {
                return ResourceManager.GetString("XivModArchive_Website", resourceCulture);
            }
        }
    }
}
