//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebUrl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebUrl() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools.Resources.WebUrl", typeof(WebUrl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 https://project.dualwield.net/bug_report_page.php 的本地化字符串。
        /// </summary>
        internal static string BugReport_Website {
            get {
                return ResourceManager.GetString("BugReport_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://FF14ChinaDiscord.esrin.tk 的本地化字符串。
        /// </summary>
        internal static string Discord_China {
            get {
                return ResourceManager.GetString("Discord_China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://discord.gg/VKhNB5g 的本地化字符串。
        /// </summary>
        internal static string Discord_Invite {
            get {
                return ResourceManager.GetString("Discord_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=B78KX56JPQFMJ&amp;source=url 的本地化字符串。
        /// </summary>
        internal static string Donate_Website {
            get {
                return ResourceManager.GetString("Donate_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://textools.dualwield.net/donate/ 的本地化字符串。
        /// </summary>
        internal static string FFXIV_Donate {
            get {
                return ResourceManager.GetString("FFXIV_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/liinko/FFXIV_TexTools_UI 的本地化字符串。
        /// </summary>
        internal static string Github_Website {
            get {
                return ResourceManager.GetString("Github_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.nexusmods.com/finalfantasy14 的本地化字符串。
        /// </summary>
        internal static string NexusMods_Website {
            get {
                return ResourceManager.GetString("NexusMods_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://prettykittyemporium.blogspot.com/ 的本地化字符串。
        /// </summary>
        internal static string PKEmporium_Website {
            get {
                return ResourceManager.GetString("PKEmporium_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://raw.githubusercontent.com/liinko/FFXIVTexToolsWeb/master/updater.xml 的本地化字符串。
        /// </summary>
        internal static string TexTools_Update_Url {
            get {
                return ResourceManager.GetString("TexTools_Update_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://textools.dualwield.net/ 的本地化字符串。
        /// </summary>
        internal static string TexTools_Website {
            get {
                return ResourceManager.GetString("TexTools_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://raw.githubusercontent.com/esrinzou/FFXIV_TexTools_Preview/master/updater.xml 的本地化字符串。
        /// </summary>
        internal static string TexToolsPre_Update_Url {
            get {
                return ResourceManager.GetString("TexToolsPre_Update_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://textools.dualwield.net/tutorials/ 的本地化字符串。
        /// </summary>
        internal static string Tutorials_Website {
            get {
                return ResourceManager.GetString("Tutorials_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.xivmodarchive.com/ 的本地化字符串。
        /// </summary>
        internal static string XivModArchive_Website {
            get {
                return ResourceManager.GetString("XivModArchive_Website", resourceCulture);
            }
        }
    }
}
