//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XivStringRaces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XivStringRaces() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools.Resources.XivStringRaces", typeof(XivStringRaces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au Ra Raen.
        /// </summary>
        internal static string Aura_R {
            get {
                return ResourceManager.GetString("Aura_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au Ra Xaela.
        /// </summary>
        internal static string Aura_X {
            get {
                return ResourceManager.GetString("Aura_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helion.
        /// </summary>
        internal static string Helion {
            get {
                return ResourceManager.GetString("Helion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyur Highlander.
        /// </summary>
        internal static string Hyur_H {
            get {
                return ResourceManager.GetString("Hyur_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyur Midlander.
        /// </summary>
        internal static string Hyur_M {
            get {
                return ResourceManager.GetString("Hyur_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        internal static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raen.
        /// </summary>
        internal static string Raen {
            get {
                return ResourceManager.GetString("Raen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rava.
        /// </summary>
        internal static string Rava {
            get {
                return ResourceManager.GetString("Rava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veena.
        /// </summary>
        internal static string Veena {
            get {
                return ResourceManager.GetString("Veena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xaela.
        /// </summary>
        internal static string Xaela {
            get {
                return ResourceManager.GetString("Xaela", resourceCulture);
            }
        }
    }
}
