//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XivStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XivStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools.Resources.XivStrings", typeof(XivStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory.
        /// </summary>
        internal static string Accessory {
            get {
                return ResourceManager.GetString("Accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodesk Collada.
        /// </summary>
        internal static string AutodeskCollada {
            get {
                return ResourceManager.GetString("AutodeskCollada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companions.
        /// </summary>
        internal static string Companions {
            get {
                return ResourceManager.GetString("Companions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ears.
        /// </summary>
        internal static string Ears {
            get {
                return ResourceManager.GetString("Ears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Decals.
        /// </summary>
        internal static string Equip_Decals {
            get {
                return ResourceManager.GetString("Equip_Decals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -decal_{0}.tex.
        /// </summary>
        internal static string EquipDecalFile {
            get {
                return ResourceManager.GetString("EquipDecalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/common/texture/decal_equip.
        /// </summary>
        internal static string EquipDecalFolder {
            get {
                return ResourceManager.GetString("EquipDecalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etc.
        /// </summary>
        internal static string Etc {
            get {
                return ResourceManager.GetString("Etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face.
        /// </summary>
        internal static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Paint.
        /// </summary>
        internal static string Face_Paint {
            get {
                return ResourceManager.GetString("Face_Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _decal_{0}.tex.
        /// </summary>
        internal static string FacePaintFile {
            get {
                return ResourceManager.GetString("FacePaintFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/common/texture/decal_face.
        /// </summary>
        internal static string FacePaintFolder {
            get {
                return ResourceManager.GetString("FacePaintFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        internal static string Furniture {
            get {
                return ResourceManager.GetString("Furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        internal static string Gear {
            get {
                return ResourceManager.GetString("Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair.
        /// </summary>
        internal static string Hair {
            get {
                return ResourceManager.GetString("Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        internal static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing.
        /// </summary>
        internal static string Housing {
            get {
                return ResourceManager.GetString("Housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD.
        /// </summary>
        internal static string HUD {
            get {
                return ResourceManager.GetString("HUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iris.
        /// </summary>
        internal static string Iris {
            get {
                return ResourceManager.GetString("Iris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        internal static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Screen.
        /// </summary>
        internal static string Loading_Screen {
            get {
                return ResourceManager.GetString("Loading_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Screen.
        /// </summary>
        internal static string LoadingScreen {
            get {
                return ResourceManager.GetString("LoadingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh.
        /// </summary>
        internal static string Mesh {
            get {
                return ResourceManager.GetString("Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minions.
        /// </summary>
        internal static string Minions {
            get {
                return ResourceManager.GetString("Minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XivMods.json.
        /// </summary>
        internal static string ModlistFilePath {
            get {
                return ResourceManager.GetString("ModlistFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        internal static string Monster {
            get {
                return ResourceManager.GetString("Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounts.
        /// </summary>
        internal static string Mounts {
            get {
                return ResourceManager.GetString("Mounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        internal static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenCOLLADA.
        /// </summary>
        internal static string OpenCollada {
            get {
                return ResourceManager.GetString("OpenCollada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring Left.
        /// </summary>
        internal static string Ring_Left {
            get {
                return ResourceManager.GetString("Ring_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring Right.
        /// </summary>
        internal static string Ring_Right {
            get {
                return ResourceManager.GetString("Ring_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail.
        /// </summary>
        internal static string Tail {
            get {
                return ResourceManager.GetString("Tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TexTools.
        /// </summary>
        internal static string TexTools {
            get {
                return ResourceManager.GetString("TexTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Map.
        /// </summary>
        internal static string Texture_Map {
            get {
                return ResourceManager.GetString("Texture_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Part.
        /// </summary>
        internal static string TypePart {
            get {
                return ResourceManager.GetString("TypePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        internal static string UI {
            get {
                return ResourceManager.GetString("UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULD.
        /// </summary>
        internal static string ULD {
            get {
                return ResourceManager.GetString("ULD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrists.
        /// </summary>
        internal static string Wrists {
            get {
                return ResourceManager.GetString("Wrists", resourceCulture);
            }
        }
    }
}
