//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XivStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XivStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools.Resources.XivStrings", typeof(XivStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Accessory 的本地化字符串。
        /// </summary>
        internal static string Accessory {
            get {
                return ResourceManager.GetString("Accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autodesk Collada 的本地化字符串。
        /// </summary>
        internal static string AutodeskCollada {
            get {
                return ResourceManager.GetString("AutodeskCollada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body 的本地化字符串。
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body + Hands + Legs 的本地化字符串。
        /// </summary>
        internal static string Body_Hands_Legs {
            get {
                return ResourceManager.GetString("Body_Hands_Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body + Hands + Legs + Feet 的本地化字符串。
        /// </summary>
        internal static string Body_Hands_Legs_Feet {
            get {
                return ResourceManager.GetString("Body_Hands_Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body + Legs + Feet 的本地化字符串。
        /// </summary>
        internal static string Body_Legs_Feet {
            get {
                return ResourceManager.GetString("Body_Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character 的本地化字符串。
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Companions 的本地化字符串。
        /// </summary>
        internal static string Companions {
            get {
                return ResourceManager.GetString("Companions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ears 的本地化字符串。
        /// </summary>
        internal static string Ears {
            get {
                return ResourceManager.GetString("Ears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment Decals 的本地化字符串。
        /// </summary>
        internal static string Equip_Decals {
            get {
                return ResourceManager.GetString("Equip_Decals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -decal_{0}.tex 的本地化字符串。
        /// </summary>
        internal static string EquipDecalFile {
            get {
                return ResourceManager.GetString("EquipDecalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/common/texture/decal_equip 的本地化字符串。
        /// </summary>
        internal static string EquipDecalFolder {
            get {
                return ResourceManager.GetString("EquipDecalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Etc 的本地化字符串。
        /// </summary>
        internal static string Etc {
            get {
                return ResourceManager.GetString("Etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Face 的本地化字符串。
        /// </summary>
        internal static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Face Paint 的本地化字符串。
        /// </summary>
        internal static string Face_Paint {
            get {
                return ResourceManager.GetString("Face_Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _decal_{0}.tex 的本地化字符串。
        /// </summary>
        internal static string FacePaintFile {
            get {
                return ResourceManager.GetString("FacePaintFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/common/texture/decal_face 的本地化字符串。
        /// </summary>
        internal static string FacePaintFolder {
            get {
                return ResourceManager.GetString("FacePaintFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feet 的本地化字符串。
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Food 的本地化字符串。
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Furniture 的本地化字符串。
        /// </summary>
        internal static string Furniture {
            get {
                return ResourceManager.GetString("Furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gear 的本地化字符串。
        /// </summary>
        internal static string Gear {
            get {
                return ResourceManager.GetString("Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hair 的本地化字符串。
        /// </summary>
        internal static string Hair {
            get {
                return ResourceManager.GetString("Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hands 的本地化字符串。
        /// </summary>
        internal static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Head 的本地化字符串。
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Head + Body 的本地化字符串。
        /// </summary>
        internal static string Head_Body {
            get {
                return ResourceManager.GetString("Head_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Housing 的本地化字符串。
        /// </summary>
        internal static string Housing {
            get {
                return ResourceManager.GetString("Housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HUD 的本地化字符串。
        /// </summary>
        internal static string HUD {
            get {
                return ResourceManager.GetString("HUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Iris 的本地化字符串。
        /// </summary>
        internal static string Iris {
            get {
                return ResourceManager.GetString("Iris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legs 的本地化字符串。
        /// </summary>
        internal static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legs + Feet 的本地化字符串。
        /// </summary>
        internal static string Legs_Feet {
            get {
                return ResourceManager.GetString("Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading Screen 的本地化字符串。
        /// </summary>
        internal static string Loading_Screen {
            get {
                return ResourceManager.GetString("Loading_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading Screen 的本地化字符串。
        /// </summary>
        internal static string LoadingScreen {
            get {
                return ResourceManager.GetString("LoadingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Hand 的本地化字符串。
        /// </summary>
        internal static string Main_Hand {
            get {
                return ResourceManager.GetString("Main_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Hand + Off Hand 的本地化字符串。
        /// </summary>
        internal static string Main_Off {
            get {
                return ResourceManager.GetString("Main_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maps 的本地化字符串。
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mesh 的本地化字符串。
        /// </summary>
        internal static string Mesh {
            get {
                return ResourceManager.GetString("Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minions 的本地化字符串。
        /// </summary>
        internal static string Minions {
            get {
                return ResourceManager.GetString("Minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XivMods.json 的本地化字符串。
        /// </summary>
        internal static string ModlistFilePath {
            get {
                return ResourceManager.GetString("ModlistFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monster 的本地化字符串。
        /// </summary>
        internal static string Monster {
            get {
                return ResourceManager.GetString("Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mounts 的本地化字符串。
        /// </summary>
        internal static string Mounts {
            get {
                return ResourceManager.GetString("Mounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Neck 的本地化字符串。
        /// </summary>
        internal static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number 的本地化字符串。
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off Hand 的本地化字符串。
        /// </summary>
        internal static string Off_Hand {
            get {
                return ResourceManager.GetString("Off_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenCOLLADA 的本地化字符串。
        /// </summary>
        internal static string OpenCollada {
            get {
                return ResourceManager.GetString("OpenCollada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part 的本地化字符串。
        /// </summary>
        internal static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pets 的本地化字符串。
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Race 的本地化字符串。
        /// </summary>
        internal static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ring Left 的本地化字符串。
        /// </summary>
        internal static string Ring_Left {
            get {
                return ResourceManager.GetString("Ring_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ring Right 的本地化字符串。
        /// </summary>
        internal static string Ring_Right {
            get {
                return ResourceManager.GetString("Ring_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rings 的本地化字符串。
        /// </summary>
        internal static string Rings {
            get {
                return ResourceManager.GetString("Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soul Crystal 的本地化字符串。
        /// </summary>
        internal static string Soul_Crystal {
            get {
                return ResourceManager.GetString("Soul_Crystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tail 的本地化字符串。
        /// </summary>
        internal static string Tail {
            get {
                return ResourceManager.GetString("Tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TexTools 的本地化字符串。
        /// </summary>
        internal static string TexTools {
            get {
                return ResourceManager.GetString("TexTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture Map 的本地化字符串。
        /// </summary>
        internal static string Texture_Map {
            get {
                return ResourceManager.GetString("Texture_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two Handed 的本地化字符串。
        /// </summary>
        internal static string Two_Handed {
            get {
                return ResourceManager.GetString("Two_Handed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type Part 的本地化字符串。
        /// </summary>
        internal static string TypePart {
            get {
                return ResourceManager.GetString("TypePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI 的本地化字符串。
        /// </summary>
        internal static string UI {
            get {
                return ResourceManager.GetString("UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ULD 的本地化字符串。
        /// </summary>
        internal static string ULD {
            get {
                return ResourceManager.GetString("ULD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waist 的本地化字符串。
        /// </summary>
        internal static string Waist {
            get {
                return ResourceManager.GetString("Waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrists 的本地化字符串。
        /// </summary>
        internal static string Wrists {
            get {
                return ResourceManager.GetString("Wrists", resourceCulture);
            }
        }
    }
}
