//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FFXIV_Directory {
            get {
                return ((string)(this["FFXIV_Directory"]));
            }
            set {
                this["FFXIV_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Save_Directory {
            get {
                return ((string)(this["Save_Directory"]));
            }
            set {
                this["Save_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_Language {
            get {
                return ((string)(this["Application_Language"]));
            }
            set {
                this["Application_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseLight")]
        public string Application_Theme {
            get {
                return ((string)(this["Application_Theme"]));
            }
            set {
                this["Application_Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF777777")]
        public string BG_Color {
            get {
                return ((string)(this["BG_Color"]));
            }
            set {
                this["BG_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public string DX_Version {
            get {
                return ((string)(this["DX_Version"]));
            }
            set {
                this["DX_Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Backup_Directory {
            get {
                return ((string)(this["Backup_Directory"]));
            }
            set {
                this["Backup_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModPack_Directory {
            get {
                return ((string)(this["ModPack_Directory"]));
            }
            set {
                this["ModPack_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hyur Midlander")]
        public string Default_Race {
            get {
                return ((string)(this["Default_Race"]));
            }
            set {
                this["Default_Race"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF5B6E81")]
        public string Hair_Highlight_Color {
            get {
                return ((string)(this["Hair_Highlight_Color"]));
            }
            set {
                this["Hair_Highlight_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF603913")]
        public string Eye_Color {
            get {
                return ((string)(this["Eye_Color"]));
            }
            set {
                this["Eye_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#998B372E")]
        public string Lip_Color {
            get {
                return ((string)(this["Lip_Color"]));
            }
            set {
                this["Lip_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF307066")]
        public string Tattoo_Color {
            get {
                return ((string)(this["Tattoo_Color"]));
            }
            set {
                this["Tattoo_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF8D3CCC")]
        public string Furniture_Color {
            get {
                return ((string)(this["Furniture_Color"]));
            }
            set {
                this["Furniture_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Back")]
        public string Cull_Mode {
            get {
                return ((string)(this["Cull_Mode"]));
            }
            set {
                this["Cull_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FFXIV_Version {
            get {
                return ((string)(this["FFXIV_Version"]));
            }
            set {
                this["FFXIV_Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Default_Race_Selection {
            get {
                return ((string)(this["Default_Race_Selection"]));
            }
            set {
                this["Default_Race_Selection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Default_Author {
            get {
                return ((string)(this["Default_Author"]));
            }
            set {
                this["Default_Author"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NameSort")]
        public string ModList_Sorting {
            get {
                return ((string)(this["ModList_Sorting"]));
            }
            set {
                this["ModList_Sorting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item")]
        public string ModList_Filter {
            get {
                return ((string)(this["ModList_Filter"]));
            }
            set {
                this["ModList_Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ForceUV1QuadrantForGear {
            get {
                return ((bool)(this["ForceUV1QuadrantForGear"]));
            }
            set {
                this["ForceUV1QuadrantForGear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloneUV1toUV2ForHair {
            get {
                return ((bool)(this["CloneUV1toUV2ForHair"]));
            }
            set {
                this["CloneUV1toUV2ForHair"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportTexDDS {
            get {
                return ((bool)(this["ExportTexDDS"]));
            }
            set {
                this["ExportTexDDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportTexBMP {
            get {
                return ((bool)(this["ExportTexBMP"]));
            }
            set {
                this["ExportTexBMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportTexPNG {
            get {
                return ((bool)(this["ExportTexPNG"]));
            }
            set {
                this["ExportTexPNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFDBB89A")]
        public string Skin_Color {
            get {
                return ((string)(this["Skin_Color"]));
            }
            set {
                this["Skin_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF6E4D23")]
        public string Hair_Color {
            get {
                return ((string)(this["Hair_Color"]));
            }
            set {
                this["Hair_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFAC719F")]
        public string Iris_Color {
            get {
                return ((string)(this["Iris_Color"]));
            }
            set {
                this["Iris_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF603913")]
        public string Etc_Color {
            get {
                return ((string)(this["Etc_Color"]));
            }
            set {
                this["Etc_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sync_Views {
            get {
                return ((bool)(this["Sync_Views"]));
            }
            set {
                this["Sync_Views"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Remember_Race_Selection {
            get {
                return ((bool)(this["Remember_Race_Selection"]));
            }
            set {
                this["Remember_Race_Selection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportAllBones {
            get {
                return ((bool)(this["ExportAllBones"]));
            }
            set {
                this["ExportAllBones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOriginalShapeDataForFace {
            get {
                return ((bool)(this["UseOriginalShapeDataForFace"]));
            }
            set {
                this["UseOriginalShapeDataForFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Default_Modpack_Url {
            get {
                return ((string)(this["Default_Modpack_Url"]));
            }
            set {
                this["Default_Modpack_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoMaterialFix {
            get {
                return ((bool)(this["AutoMaterialFix"]));
            }
            set {
                this["AutoMaterialFix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FixPreDawntrailOnImport {
            get {
                return ((bool)(this["FixPreDawntrailOnImport"]));
            }
            set {
                this["FixPreDawntrailOnImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LiveDangerously {
            get {
                return ((bool)(this["LiveDangerously"]));
            }
            set {
                this["LiveDangerously"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PenumbraFolder {
            get {
                return ((string)(this["PenumbraFolder"]));
            }
            set {
                this["PenumbraFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenTransactionOnStart {
            get {
                return ((bool)(this["OpenTransactionOnStart"]));
            }
            set {
                this["OpenTransactionOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShiftExportUV {
            get {
                return ((bool)(this["ShiftExportUV"]));
            }
            set {
                this["ShiftExportUV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShiftImportUV {
            get {
                return ((bool)(this["ShiftImportUV"]));
            }
            set {
                this["ShiftImportUV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModelingTool {
            get {
                return ((string)(this["ModelingTool"]));
            }
            set {
                this["ModelingTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FixPreDawntrailPartialOnImport {
            get {
                return ((bool)(this["FixPreDawntrailPartialOnImport"]));
            }
            set {
                this["FixPreDawntrailPartialOnImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxImageSize {
            get {
                return ((int)(this["MaxImageSize"]));
            }
            set {
                this["MaxImageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CompressEndwalkerUpgradeTextures {
            get {
                return ((bool)(this["CompressEndwalkerUpgradeTextures"]));
            }
            set {
                this["CompressEndwalkerUpgradeTextures"] = value;
            }
        }
    }
}
